/**
 * seedMed_p3.js — 40 médicaments
 * Classe 6 : Diurétiques (drogues 2-10)
 * Classe 7 : Benzodiazépines (drogues 2-10)
 * Classe 8 : Antidiabétiques (drogues 2-10)
 * Classe 9 : Antidépresseurs (drogues 2-10)
 */

function s(general, tags) {
  return {
    sections: [
      { title: 'Général', content: general, order: 0 },
      { title: 'Médias',  content: 'Schémas et ressources pédagogiques disponibles dans les supports de cours IFSI et sur le site de l\'ANSM.', order: 1 },
      { title: 'Source',  content: '**Références**\n1. ANSM — Monographie du médicament. [ansm.sante.fr]\n2. Vidal — Fiche médicament. [vidal.fr]\n3. HAS — Recommandations de bon usage. [has-sante.fr]\n4. Société savante de référence — Recommandations cliniques.', order: 2 },
    ],
    sources: [
      { title: 'ANSM — Monographie', authors: 'ANSM', year: '2023', url: 'https://ansm.sante.fr' },
      { title: 'Vidal',              authors: 'Vidal', year: '2023', url: 'https://vidal.fr' },
    ],
    tags,
  };
}

/* ══════════════════════════════════════════════════════════════
   CLASSE 6 — Diurétiques (anse + thiazidiques + épargneurs K+)
══════════════════════════════════════════════════════════════ */

const diuretiques = [

  { classIndex: 6, name: 'Bumétanide (Burinex®)', genericName: 'Bumétanide', description: 'Diurétique de l\'anse, 40 fois plus puissant que le furosémide à masse égale. Bonne biodisponibilité orale. Alternative au furosémide.',
    ...s(`**DCI :** Bumétanide\n**Noms commerciaux :** Burinex®\n\n**Mécanisme d'action**\nInhibiteur du co-transporteur NKCC2 dans l'anse de Henlé, comme le furosémide. 40 fois plus puissant à masse égale (1 mg bumétanide ≈ 40 mg furosémide). Bonne biodisponibilité orale (80-90%) même en cas d'insuffisance cardiaque (contrairement au furosémide dont l'absorption orale est inconstante dans l'IC sévère).\n\n**Indications principales**\n- Œdèmes d'origine cardiaque, rénale ou hépatique\n- Insuffisance cardiaque congestive, OAP\n- Résistance au furosémide (alternative)\n\n**Posologie adulte**\n- Per os : 0,5 à 2 mg/j en 1-2 prises\n- IV : 0,5 à 1 mg en injection lente\n\n**Contre-indications**\n- Anurie, déshydratation sévère\n- Hypokaliémie non corrigée\n\n**Effets indésirables**\n- Hypokaliémie (même précaution que furosémide)\n- Déshydratation, hyponatrémie\n- Ototoxicité (rare)\n\n**Surveillance infirmière**\n- Kaliémie, natrémie, créatinine\n- Balance entrées/sorties\n- Poids quotidien\n- PA (hypotension orthostatique)`, ['diurétique', 'anse de Henlé', 'bumétanide', 'IC', 'OAP', 'NKCC2', 'hypokaliémie']) },

  { classIndex: 6, name: 'Torasémide (Torem®)', genericName: 'Torasémide', description: 'Diurétique de l\'anse à plus longue durée d\'action que le furosémide. Meilleure biodisponibilité orale et moindre risque de résistance.',
    ...s(`**DCI :** Torasémide\n**Noms commerciaux :** Torem®\n\n**Mécanisme d'action**\nInhibiteur NKCC2 (anse de Henlé), même classe que furosémide. Biodisponibilité orale supérieure (~80% vs 50% variable pour furosémide). Durée d'action plus longue (6-8h vs 4-6h). Moins de rebond sodé post-diurèse. Propriété anti-aldostérone légère.\n\n**Indications principales**\n- Insuffisance cardiaque chronique (études montrent réduction des hospitalisations vs furosémide)\n- Hypertension artérielle (en complément)\n- Œdèmes d'origine cardiaque ou rénale\n\n**Posologie adulte**\n- IC : 5-20 mg/j per os en 1 prise\n- HTA : 2,5-5 mg/j\n- Max 200 mg/j en cas de résistance\n\n**Contre-indications**\n- Identiques aux autres diurétiques de l'anse\n\n**Effets indésirables**\n- Hypokaliémie (moindre que furosémide selon certaines études)\n- Déshydratation, hyponatrémie\n\n**Surveillance infirmière**\n- Mêmes surveillances que le furosémide\n- Avantage : prise unique et absorption plus prévisible`, ['diurétique', 'anse de Henlé', 'torasémide', 'IC', 'HTA', 'NKCC2', 'biodisponibilité']) },

  { classIndex: 6, name: 'Hydrochlorothiazide (Esidrex®)', genericName: 'Hydrochlorothiazide', description: 'Diurétique thiazidique de référence. Antihypertenseur en monothérapie ou association. Mécanisme différent des diurétiques de l\'anse.',
    ...s(`**DCI :** Hydrochlorothiazide (HCTZ)\n**Noms commerciaux :** Esidrex®, Hypothiazide® ; fréquemment en association (Zestoretic®, Co-Renitec®, etc.)\n\n**Mécanisme d'action**\nInhibiteur du co-transporteur NCC (Na⁺/Cl⁻) dans le tube contourné distal du néphron. Diurèse modérée, natriurèse avec perte potassique. Puissance diurétique inférieure aux diurétiques de l'anse mais durée d'action plus longue (12-24h).\n\n**Indications principales**\n- HTA essentielle (en monothérapie ou très souvent en bithérapie fixe avec IEC, ARA2 ou amlodipine)\n- Œdèmes d'origine cardiaque modérés\n- Prévention des lithiases urinaires calciques (réduction excrétion calcique)\n\n**Posologie adulte**\n- HTA : 12,5-25 mg/j per os en 1 prise le matin\n- Maximum 50 mg/j\n\n**Contre-indications**\n- Goutte évoluée (risque d'hyperuricémie)\n- Hyponatrémie, hypokaliémie sévère\n- Insuffisance rénale sévère (peu efficace si DFG < 30)\n\n**Effets indésirables**\n- Hypokaliémie (moins sévère qu'avec les diurétiques de l'anse)\n- Hyperglycémie (diabète cortisonique-like)\n- Hyperuricémie → crise de goutte\n- Hyponatrémie (surtout sujets âgés)\n- Photosensibilisation\n\n**Surveillance infirmière**\n- Ionogramme sanguin (K⁺, Na⁺) régulier\n- Glycémie à jeun\n- Uricémie si antécédents de goutte\n- PA et poids`, ['diurétique', 'thiazidique', 'hydrochlorothiazide', 'HTA', 'antihypertenseur', 'NCC', 'hypokaliémie']) },

  { classIndex: 6, name: 'Indapamide (Fludex®)', genericName: 'Indapamide', description: 'Diurétique thiazidique-like avec propriétés vasodilatatrices directes. Antihypertenseur de première intention. Moins de troubles métaboliques que l\'HCTZ.',
    ...s(`**DCI :** Indapamide\n**Noms commerciaux :** Fludex® (LP 1,5 mg), Indapamide Mylan®\n\n**Mécanisme d'action**\nDiurétique indoline, inhibiteur du NCC (tube contourné distal), mais aussi propriétés vasodilatatrices directes (inhibition canaux calciques vasculaires). Moins de perte potassique et moins d'effet métabolique (glycémie, uricémie) que l'HCTZ.\n\n**Indications principales**\n- HTA essentielle (1ère intention dans certaines recommandations)\n- Association avec périndopril (Bipreterax®) pour réduction risque CV chez diabétique\n- Insuffisance cardiaque (en alternative)\n\n**Posologie adulte**\n- 1,5 mg/j (LP) per os en 1 prise le matin\n\n**Contre-indications**\n- Allergie aux sulfamides\n- Hypokaliémie sévère\n- Insuffisance rénale sévère\n\n**Effets indésirables**\n- Hypokaliémie (moins fréquente que HCTZ)\n- Hyponatrémie\n- Photosensibilisation (sulfamide)\n\n**Surveillance infirmière**\n- Ionogramme sanguin\n- PA\n- Ne pas mélanger avec d'autres diurétiques sans prescription`, ['diurétique', 'indapamide', 'thiazidique-like', 'HTA', 'NCC', 'vasodilatateur', 'moins métabolique']) },

  { classIndex: 6, name: 'Spironolactone (Aldactone®)', genericName: 'Spironolactone', description: 'Diurétique épargnant le potassium, antagoniste de l\'aldostérone. Traitement de l\'hyperaldostéronisme, de l\'insuffisance cardiaque et de l\'ascite cirrhotique.',
    ...s(`**DCI :** Spironolactone\n**Noms commerciaux :** Aldactone®, Spironolactone Mylan®\n\n**Mécanisme d'action**\nAntagoniste compétitif et sélectif des récepteurs minéralocorticoïdes (aldostérone) dans le tube collecteur rénal → rétention potassique et excrétion sodée (diurèse modérée). Effets antiandrogéniques (propriétés anti-testostérone → effets indésirables en rapport).\n\n**Indications principales**\n- Insuffisance cardiaque systolique sévère (NYHA III-IV) — réduction de mortalité démontrée (étude RALES)\n- Ascite cirrhotique (1ère intention en association avec furosémide)\n- Hyperaldostéronisme primaire (adénome de Conn)\n- HTA résistante\n- Hirsutisme (hors AMM)\n\n**Posologie adulte**\n- IC : 25-50 mg/j per os\n- Ascite cirrhotique : 100-400 mg/j (ratio spiro/furosémide 100:40)\n- HTA résistante : 25-50 mg/j\n\n**Contre-indications**\n- Hyperkaliémie (K⁺ > 5 mmol/L)\n- Insuffisance rénale sévère (DFG < 30)\n- Association avec d'autres épargneurs potassiques ou IEC/AOD en IR\n\n**Effets indésirables**\n- Hyperkaliémie (risque majeur — surtout avec IEC, IR, AINS)\n- Gynécomastie (effet antiandrogénique)\n- Impuissance\n- Troubles des règles\n\n**Surveillance infirmière**\n- Kaliémie et créatinine avant initiation et à J7, J30\n- Surveiller signes d'hyperkaliémie : crampes, faiblesse, bradycardie, anomalies ECG\n- Expliquer la gynécomastie au patient masculin (prévisible, réversible)`, ['diurétique', 'spironolactone', 'épargnant K+', 'aldostérone', 'IC', 'ascite', 'hyperkaliémie']) },

  { classIndex: 6, name: 'Éplérénone (Inspra®)', genericName: 'Éplérénone', description: 'Antagoniste sélectif de l\'aldostérone (anti-minéralocorticoïde), plus sélectif que la spironolactone. Pas d\'effets antiandrogéniques. Indiqué en post-IDM.',
    ...s(`**DCI :** Éplérénone\n**Noms commerciaux :** Inspra®\n\n**Mécanisme d'action**\nAntagoniste sélectif des récepteurs minéralocorticoïdes. Plus sélectif que la spironolactone (pas d'affinité pour les récepteurs androgènes, progestérone) → pas de gynécomastie, pas d'impuissance. Épargnant le potassium.\n\n**Indications principales**\n- Post-IDM avec dysfonction VG (FEVG ≤ 40%) et symptômes d'IC ou diabète (étude EPHESUS)\n- Insuffisance cardiaque chronique stable avec FEVG ≤ 35% (NYHA II) — étude EMPHASIS\n\n**Posologie adulte**\n- Post-IDM : 25 mg/j initialement, objectif 50 mg/j si bien toléré (K⁺ < 5 mmol/L)\n\n**Contre-indications**\n- Hyperkaliémie (K⁺ > 5 mmol/L)\n- DFG < 30 mL/min\n- Insuffisance hépatique sévère\n\n**Effets indésirables**\n- Hyperkaliémie (principal risque)\n- Hyponatrémie\n- Pas de gynécomastie (avantage vs spironolactone)\n\n**Surveillance infirmière**\n- Kaliémie à J7, J30 après initiation\n- Créatinine\n- Avantage pour les hommes : tolérance meilleure que spironolactone`, ['diurétique', 'éplérénone', 'anti-aldostérone', 'épargnant K+', 'post-IDM', 'IC', 'sélectif']) },

  { classIndex: 6, name: 'Amiloride (Modamide®)', genericName: 'Amiloride chlorhydrate', description: 'Diurétique épargnant le potassium, bloquant les canaux sodiques épithéliaux (ENaC). Utilisé en association pour compenser la perte potassique des autres diurétiques.',
    ...s(`**DCI :** Amiloride chlorhydrate\n**Noms commerciaux :** Modamide®, Logirène® (association amiloride + furosémide)\n\n**Mécanisme d'action**\nBloque directement les canaux sodiques épithéliaux (ENaC) du tube collecteur cortical → inhibition de la réabsorption sodique sans dépendre de l'aldostérone. Épargnant le potassium. Diurèse modérée.\n\n**Indications principales**\n- Association aux diurétiques kaliurétiques (furosémide, thiazidiques) pour prévenir l'hypokaliémie\n- HTA (en association)\n- Syndrome de Liddle (mutation constitutive des ENaC)\n\n**Posologie adulte**\n- 5-10 mg/j per os, le matin, avec repas\n\n**Contre-indications**\n- Hyperkaliémie\n- Insuffisance rénale sévère\n- Association avec IEC ou ARA2 (risque d'hyperkaliémie sévère)\n\n**Effets indésirables**\n- Hyperkaliémie\n- Nausées, troubles digestifs\n\n**Surveillance infirmière**\n- Kaliémie et créatinine régulièrement\n- En association avec furosémide : surveiller le bilan K⁺ (objectif de compenser la perte)`, ['diurétique', 'amiloride', 'ENaC', 'épargnant K+', 'association', 'HTA', 'hyperkaliémie']) },

  { classIndex: 6, name: 'Acétazolamide (Diamox®)', genericName: 'Acétazolamide', description: 'Inhibiteur de l\'anhydrase carbonique. Diurétique à mécanisme unique. Utilisé dans le glaucome, l\'épilepsie et la prévention du mal aigu des montagnes.',
    ...s(`**DCI :** Acétazolamide\n**Noms commerciaux :** Diamox®\n\n**Mécanisme d'action**\nInhibiteur de l'anhydrase carbonique (enzyme catalysant CO₂ + H₂O → HCO₃⁻ + H⁺) au niveau rénal, oculaire et cérébral. Rénal : réduction de la réabsorption du bicarbonate → diurèse bicarbonatée, acidose métabolique. Oculaire : réduction de la production d'humeur aqueuse → baisse de la pression intra-oculaire.\n\n**Indications principales**\n- Glaucome chronique (réduction PIO en attente de chirurgie ou si contre-indication)\n- Prévention et traitement du mal aigu des montagnes (MAM)\n- Épilepsie réfractaire (adjuvant, surtout petit mal d'absence)\n- Alcalose métabolique (réalcalinisation par perte bicarbonate)\n\n**Posologie adulte**\n- Glaucome : 250-1 000 mg/j per os en 2-4 prises\n- MAM : 250 mg x 2/j 24h avant montée, jusqu'à stabilisation\n\n**Contre-indications**\n- Allergie aux sulfamides\n- Acidose métabolique préexistante\n- Insuffisance rénale sévère, Insuffisance hépatique sévère\n- Hyponatrémie, hypokaliémie sévère\n\n**Effets indésirables**\n- Acidose métabolique (mécanisme)\n- Paresthésies des extrémités et de la bouche (fréquentes)\n- Lithiases rénales calciques (modification pH urinaire)\n- Hypokaliémie\n\n**Surveillance infirmière**\n- Gaz du sang (pH, HCO₃⁻) si usage prolongé\n- Surveiller diurèse\n- Informer sur les paresthésies (bénignes)\n- Hydratation suffisante (prévention lithiases)`, ['diurétique', 'acétazolamide', 'anhydrase carbonique', 'glaucome', 'mal des montagnes', 'épilepsie', 'acidose']) },

  { classIndex: 6, name: 'Mannitol (Mannitol Baxter®)', genericName: 'Mannitol', description: 'Diurétique osmotique. Utilisé en urgence neurologique pour réduire l\'œdème cérébral et la pression intracrânienne. Usage exclusivement IV.',
    ...s(`**DCI :** Mannitol\n**Noms commerciaux :** Mannitol Baxter® (solution IV à 10%, 15%, 20%)\n\n**Mécanisme d'action**\nOsmodiurétique : polyol non réabsorbé filtré librement par le glomérule. Crée un gradient osmotique dans le tubule rénal → entraine l'eau dans le filtrat → diurèse osmotique. Au niveau cérébral : gradient osmotique sanguin > cérébral → déshydratation du tissu cérébral → réduction PIC.\n\n**Indications principales**\n- Hypertension intracrânienne aiguë (traumatisme crânien, AVC hémorragique, engagement cérébral)\n- Prévention de l'insuffisance rénale aiguë oligurique (en milieu chirurgical)\n- Crise de glaucome aiguë (par angle fermé) en urgence\n\n**Posologie adulte**\n- HTIC : 0,25-1 g/kg en perfusion IV rapide (15-30 min), à répéter selon réponse\n- En pratique : 250-500 mL de mannitol 20% en 30 min\n\n**Contre-indications**\n- Insuffisance rénale oligo-anurique sévère (contre-indiqué car accumulation)\n- Insuffisance cardiaque congestive (expansion volémique initiale)\n- Hémorragie intracrânienne active (discuté)\n\n**Effets indésirables**\n- Expansion volémique initiale → risque d'OAP\n- Déshydratation et hypernatrémie (rebond)\n- Insuffisance rénale (usage excessif)\n\n**Surveillance infirmière**\n- Diurèse horaire obligatoire\n- Natrémie et osmolalité plasmatique\n- Surveiller signes d'OAP (auscultation, SpO2)\n- Osmolalité plasmatique cible < 320 mOsm/kg`, ['diurétique', 'mannitol', 'osmotique', 'HTIC', 'hypertension intracrânienne', 'neurologie', 'urgence']) },
];

/* ══════════════════════════════════════════════════════════════
   CLASSE 7 — Benzodiazépines
══════════════════════════════════════════════════════════════ */

const benzodiazepines = [

  { classIndex: 7, name: 'Lorazépam (Témesta®)', genericName: 'Lorazépam', description: 'BZD de durée d\'action intermédiaire (10-20h), sans métabolites actifs. Préféré pour l\'anxiété et en sédation procédurale IV, surtout chez le sujet âgé.',
    ...s(`**DCI :** Lorazépam\n**Noms commerciaux :** Témesta®, Lorazépam Mylan®\n\n**Mécanisme d'action**\nAgoniste des récepteurs GABA-A (potentialisation GABA). Durée d'action intermédiaire (12-16h). Pas de métabolites actifs → accumulation moindre, surtout chez le sujet âgé et l'insuffisant hépatique.\n\n**Indications principales**\n- Anxiété sévère et invalidante (traitement court ≤ 4 semaines)\n- Insomnie dans le cadre de l'anxiété\n- Sédation procédurale et prémédication\n- État de mal épileptique (IV en 2ème ligne)\n- Agitation aiguë (IM)\n\n**Posologie adulte**\n- Anxiété : 0,5 à 2 mg/j en 2-3 prises\n- Sédation IV : 1-2 mg IV lente\n- IM : 2-4 mg\n\n**Contre-indications**\n- Insuffisance respiratoire sévère\n- Myasthénie grave\n- Association avec l'alcool\n\n**Effets indésirables**\n- Somnolence, amnésie\n- Dépression respiratoire (IV)\n- Dépendance physique et psychique\n\n**Surveillance infirmière**\n- FR et SpO2 si administration IV\n- Risque de chute (surtout sujet âgé)\n- Pas de métabolites actifs : avantage chez le sujet âgé (règle des « 3 P » : prescriptions pédiatriques, personnes âgées, pathologies hépatiques → lorazépam ou oxazépam préférés)`, ['benzodiazépine', 'lorazépam', 'GABA', 'anxiolytique', 'sujet âgé', 'sédation', 'pas de métabolites actifs']) },

  { classIndex: 7, name: 'Alprazolam (Xanax®)', genericName: 'Alprazolam', description: 'BZD de courte à moyenne durée d\'action (demi-vie 6-27h). Anxiolytique puissant. Fort potentiel de dépendance. Très largement prescrit mais usage problématique.',
    ...s(`**DCI :** Alprazolam\n**Noms commerciaux :** Xanax®\n\n**Mécanisme d'action**\nAgoniste BZD haute affinité. Courte à moyenne durée d'action. Puissance anxiolytique élevée. Demi-vie 6-27h (métabolites partiellement actifs). Fort potentiel de dépendance physique et psychique.\n\n**Indications principales**\n- Trouble panique avec ou sans agoraphobie\n- Anxiété généralisée sévère\n- Anxiété situationnelle (usage ponctuel)\n\n**Posologie adulte**\n- Anxiété : 0,25-0,5 mg x 3/j\n- Trouble panique : 0,5-1 mg x 3/j (titration)\n\n**Contre-indications**\n- Insuffisance respiratoire sévère\n- Association avec opioïdes (synergisme dépression respiratoire)\n\n**Effets indésirables**\n- Fort potentiel addictif\n- Syndrome de sevrage sévère à l'arrêt brutal (crises convulsives possibles)\n- Somnolence, amnésie, sédation\n\n**Surveillance infirmière**\n- Limiter la durée (max 8-12 semaines)\n- Arrêt TOUJOURS progressif\n- Évaluer régulièrement la nécessité de poursuite\n- Éduquer sur la dépendance`, ['benzodiazépine', 'alprazolam', 'Xanax', 'anxiolytique', 'trouble panique', 'dépendance', 'sevrage']) },

  { classIndex: 7, name: 'Midazolam (Hypnovel®)', genericName: 'Midazolam chlorhydrate', description: 'BZD à très courte durée d\'action (2-4h). Usage en anesthésie, sédation palliative et état de mal épileptique. Antagonisable par le flumazénil.',
    ...s(`**DCI :** Midazolam chlorhydrate\n**Noms commerciaux :** Hypnovel®, Buccolam® (solution buccale pédiatrique)\n\n**Mécanisme d'action**\nBZD hydrosoluble (stable en solution) à courte durée d'action et forte puissance. Très liposoluble après injection → action rapide. Demi-vie courte (1,5-2,5h). Effets : anxiolytique, sédatif, amnésiant (amnésie antérograde), anticonvulsivant, myorelaxant.\n\n**Indications principales**\n- Prémédication anesthésique (IM ou IV)\n- Sédation procédurale (endoscopie, ventilation assistée)\n- Induction de l'anesthésie (IV)\n- État de mal épileptique (voie buccale ou nasale hors AMM)\n- Sédation palliative (IVSE)\n\n**Posologie adulte**\n- Prémédication : 7,5 mg per os 30-60 min avant, ou 1-5 mg IV titré\n- Sédation IVSE : 0,03-0,1 mg/kg/h\n- Epilepsie buccale : 10 mg par voie buccale (Buccolam®)\n\n**Contre-indications**\n- Insuffisance respiratoire sévère non assistée\n- Myasthénie\n\n**Effets indésirables**\n- Dépression respiratoire (IV — risque majeur)\n- Amnésie antérograde (effet recherché en procédure)\n- Dépendance si usage prolongé\n\n**Antidote :** Flumazénil (Anexate®)\n\n**Surveillance infirmière**\n- Monitoring continu : SpO2, FR, PA, FC\n- Matériel de réanimation disponible\n- Patient à jeun pour les procédures\n- Durée de réveil courte : surveiller jusqu'à réveil complet`, ['benzodiazépine', 'midazolam', 'Hypnovel', 'anesthésie', 'sédation', 'palliative', 'flumazénil']) },

  { classIndex: 7, name: 'Clonazépam (Rivotril®)', genericName: 'Clonazépam', description: 'BZD antiépileptique de référence. Utilisé dans les épilepsies réfractaires et l\'état de mal épileptique. Demi-vie longue (18-50h). Classé stupéfiant.',
    ...s(`**DCI :** Clonazépam\n**Noms commerciaux :** Rivotril®\n\n**Mécanisme d'action**\nAgoniste BZD avec propriétés antiépileptiques marquées (haute affinité pour les récepteurs BZD1 et BZD2). Longue demi-vie (18-50h). Puissant anticonvulsivant.\n\n**Indications principales**\n- Épilepsies généralisées : absences, myoclonies, Lennox-Gastaut\n- Épilepsies partielles réfractaires aux autres traitements\n- État de mal épileptique (IV)\n\n**Posologie adulte**\n- Per os : 1-2 mg/j initialement, max 20 mg/j en doses fractionnées\n- IV pour état de mal : 1 mg IV lente, répétable\n\n**Contre-indications**\n- Insuffisance respiratoire sévère\n- Insuffisance hépatique sévère\n- Myasthénie\n\n**Effets indésirables**\n- Somnolence importante (sédation)\n- Hypersalivation (surtout pédiatrie)\n- Dépression respiratoire\n- Tolérance et dépendance\n\n**Surveillance infirmière**\n- FR et SpO2 lors des injections IV\n- Surveiller la tolérance (somnolence peut nécessiter adaptation posologique)\n- Traçabilité stricte (stupéfiant)\n- Éduquer sur les risques d'interactions (alcool, autres psychotropes)`, ['benzodiazépine', 'clonazépam', 'Rivotril', 'antiépileptique', 'état de mal', 'épilepsie', 'stupéfiant']) },

  { classIndex: 7, name: 'Bromazépam (Lexomil®)', genericName: 'Bromazépam', description: 'BZD anxiolytique de demi-vie intermédiaire (20h). L\'une des benzodiazépines les plus prescrites en France. Potentiel de dépendance important.',
    ...s(`**DCI :** Bromazépam\n**Noms commerciaux :** Lexomil®\n\n**Mécanisme d'action**\nAgoniste GABA-A, demi-vie intermédiaire (~20h). Métabolite actif (hydroxybromazépam). Propriétés anxiolytiques prédominantes.\n\n**Indications principales**\n- Anxiété sévère et invalidante (traitement court ≤ 12 semaines)\n- Insomnie transitoire liée à l'anxiété\n\n**Posologie adulte**\n- 1,5 à 6 mg/j en 2-3 prises\n- Comprimés sécables (1,5 mg)\n\n**Contre-indications**\n- Insuffisance respiratoire\n- Myasthénie, syndrome apnées du sommeil\n\n**Effets indésirables**\n- Somnolence diurne, altération des performances cognitives\n- Dépendance physique et psychique\n- Syndrome de sevrage à l'arrêt\n\n**Surveillance infirmière**\n- Réévaluation régulière de l'indication\n- Ne pas arrêter brutalement (décroissance sur plusieurs semaines)\n- Risque de chute (surtout sujet âgé)\n- Éviter chez le sujet > 65 ans`, ['benzodiazépine', 'bromazépam', 'Lexomil', 'anxiolytique', 'dépendance', 'sujet âgé']) },

  { classIndex: 7, name: 'Oxazépam (Séresta®)', genericName: 'Oxazépam', description: 'BZD à courte durée d\'action (4-8h), sans métabolites actifs. Préféré chez le sujet âgé et l\'insuffisant hépatique. Traitement du sevrage alcoolique.',
    ...s(`**DCI :** Oxazépam\n**Noms commerciaux :** Séresta®\n\n**Mécanisme d'action**\nAgoniste BZD à courte demi-vie (4-8h). Pas de métabolites actifs (conjugaison directe en glucuronide) → pas d'accumulation, idéal chez la personne âgée et l'insuffisant hépatique (règle des « 3 P »).\n\n**Indications principales**\n- Anxiété sévère chez la personne âgée (BZD de choix)\n- Anxiété chez l'insuffisant hépatique\n- Sevrage alcoolique (protocoles dégressifs)\n\n**Posologie adulte**\n- Anxiété : 10-30 mg x 2-4/j\n- Sevrage alcoolique : 30-90 mg/j selon sevrage CIWA-Ar\n\n**Contre-indications**\n- Insuffisance respiratoire\n- Myasthénie\n\n**Effets indésirables**\n- Moins de sédation résiduelle (demi-vie courte)\n- Dépendance si prolongé\n\n**Surveillance infirmière**\n- BZD de référence chez le sujet âgé et en hépathologie\n- Sevrage alcoolique : score CIWA-Ar avant chaque administration\n- Décroissance progressive à l'arrêt`, ['benzodiazépine', 'oxazépam', 'Séresta', 'sujet âgé', 'insuffisance hépatique', 'sevrage alcoolique', 'courte demi-vie']) },

  { classIndex: 7, name: 'Clorazépate (Tranxène®)', genericName: 'Clorazépate dipotassique', description: 'Prodrogue de longue durée d\'action, transformée en nordazépam (demi-vie 50-100h). Anxiolytique et traitement du sevrage alcoolique.',
    ...s(`**DCI :** Clorazépate dipotassique\n**Noms commerciaux :** Tranxène®\n\n**Mécanisme d'action**\nProdrogue rapidement convertie en nordazépam (N-desméthyldiazépam, demi-vie 50-100h). BZD à très longue durée d'action effective. Risque d'accumulation important chez le sujet âgé et l'insuffisant hépatique.\n\n**Indications principales**\n- Anxiété sévère (traitement court)\n- Sevrage alcoolique (en hospitalisation, schéma dégressif)\n- Épilepsie (adjuvant)\n\n**Posologie adulte**\n- Anxiété : 5-40 mg/j en 2-3 prises\n- Sevrage alcoolique : 100-200 mg/j en J1 avec décroissance\n\n**Contre-indications**\n- Insuffisance respiratoire sévère\n- Sujet âgé (accumulation nordazépam)\n\n**Effets indésirables**\n- Accumulation marquée (longue demi-vie)\n- Somnolence prolongée\n- Dépendance forte\n\n**Surveillance infirmière**\n- Sevrage alcoolique : en milieu hospitalier, monitoring régulier\n- Éviter chez le sujet > 65 ans (risque d'accumulation et de chutes)\n- Décroissance lente à l'arrêt`, ['benzodiazépine', 'clorazépate', 'Tranxène', 'nordazépam', 'sevrage alcoolique', 'anxiolytique', 'longue demi-vie']) },

  { classIndex: 7, name: 'Nitrazépam (Mogadon®)', genericName: 'Nitrazépam', description: 'BZD hypnotique à demi-vie longue (15-38h). Utilisé dans les insomnies sévères. Potentiel de sédation résiduelle diurne important.',
    ...s(`**DCI :** Nitrazépam\n**Noms commerciaux :** Mogadon®\n\n**Mécanisme d'action**\nAgoniste BZD à propriétés hypnotiques marquées. Demi-vie longue (15-38h) → risque de sédation résiduelle le lendemain (effet « gueule de bois »). Métabolisme hépatique.\n\n**Indications principales**\n- Insomnie sévère et invalidante (durée limitée ≤ 4 semaines)\n- En particulier insomnie d'endormissement et de maintien du sommeil\n\n**Posologie adulte**\n- 5 mg au coucher (2,5 mg chez le sujet âgé)\n- Durée maximale recommandée : 4 semaines\n\n**Contre-indications**\n- Syndrome d'apnées du sommeil\n- Insuffisance respiratoire sévère\n- Myasthénie\n\n**Effets indésirables**\n- Somnolence diurne persistante (longue demi-vie)\n- Altération des performances cognitives\n- Dépendance\n- Risque de chute (nocturne)\n\n**Surveillance infirmière**\n- Risque de chute nocturne : barrières de lit, éclairage nocturne\n- Informer le patient de la somnolence résiduelle (ne pas conduire)\n- Durée limitée, arrêt progressif`, ['benzodiazépine', 'nitrazépam', 'Mogadon', 'hypnotique', 'insomnie', 'sédation résiduelle', 'chute']) },

  { classIndex: 7, name: 'Clobazam (Urbanyl®)', genericName: 'Clobazam', description: 'BZD 1,5 (différente des BZD 1,4). Profil antiépileptique marqué avec moindre sédation comparativement. Utilisé en adjuvant de l\'épilepsie.',
    ...s(`**DCI :** Clobazam\n**Noms commerciaux :** Urbanyl®\n\n**Mécanisme d'action**\nBenzodiaépine de structure 1,5 (différente des BZD classiques 1,4). Se lie aux récepteurs GABA-A mais avec moins d'affinité pour les récepteurs responsables de la sédation → moins sédatif que les autres BZD à dose antiépileptique équivalente.\n\n**Indications principales**\n- Épilepsie en traitement adjuvant (surtout syndrome de Lennox-Gastaut)\n- Anxiété sévère (courte durée)\n\n**Posologie adulte**\n- Épilepsie : 20-40 mg/j en 2 prises\n- Anxiété : 20-30 mg/j\n\n**Contre-indications**\n- Insuffisance respiratoire sévère\n- Myasthénie\n\n**Effets indésirables**\n- Moins sédatif que les autres BZD\n- Tolérance épileptique (perte d'efficacité au fil du temps)\n- Dépendance\n\n**Surveillance infirmière**\n- Surveiller la fréquence et le type de crises (journal épileptique)\n- Évaluer le niveau de sédation\n- Arrêt progressif si décision d'arrêt`, ['benzodiazépine', 'clobazam', 'Urbanyl', 'antiépileptique', '1,5-BZD', 'Lennox-Gastaut', 'épilepsie']) },
];

/* ══════════════════════════════════════════════════════════════
   CLASSE 8 — Antidiabétiques
══════════════════════════════════════════════════════════════ */

const antidiabetiques = [

  { classIndex: 8, name: 'Glibenclamide (Daonil®)', genericName: 'Glibenclamide', description: 'Sulfonylurée de 2ème génération. Stimule la sécrétion d\'insuline. Risque d\'hypoglycémie important, surtout chez le sujet âgé. Déconseillé après 70 ans.',
    ...s(`**DCI :** Glibenclamide\n**Noms commerciaux :** Daonil®, Hemi-Daonil®\n\n**Mécanisme d'action**\nSulfonylurée (sulfamide hypoglycémiant) : se lie au récepteur SUR1 des cellules bêta du pancréas → fermeture des canaux K⁺-ATP → dépolarisation → entrée Ca²⁺ → exocytose de l'insuline. Stimulation insulinosécrétion indépendante de la glycémie → risque d'hypoglycémie même à jeun.\n\n**Indications principales**\n- Diabète de type 2 (palier 2 après metformine si objectif non atteint)\n- En association avec la metformine ou l'insuline basale\n\n**Posologie adulte**\n- 2,5 à 15 mg/j per os en 1-3 prises selon la glycémie\n- À prendre juste avant les repas\n\n**Contre-indications**\n- Diabète de type 1\n- Insuffisance rénale (accumulation → hypoglycémie)\n- Insuffisance hépatique sévère\n- Sujet âgé fragile (risque hypoglycémie sévère et prolongée)\n- Grossesse\n\n**Effets indésirables**\n- Hypoglycémie (risque principal et majeur)\n- Prise de poids\n- Réactions cutanées allergiques\n\n**Surveillance infirmière**\n- Glycémie capillaire régulière\n- Éduquer sur les symptômes d'hypoglycémie : sueurs, tremblements, palpitations, confusion\n- Réserve glucosée disponible (sucre)\n- À éviter chez les > 70 ans et en cas d'irrégularités alimentaires`, ['antidiabétique', 'sulfonylurée', 'glibenclamide', 'insulinosécréteur', 'DT2', 'hypoglycémie', 'pancréas']) },

  { classIndex: 8, name: 'Gliclazide (Diamicron®)', genericName: 'Gliclazide', description: 'Sulfonylurée de 2ème génération avec propriétés antioxydantes supplémentaires. Moins de risque d\'hypoglycémie que le glibenclamide. Disponible en forme LP (1 prise/j).',
    ...s(`**DCI :** Gliclazide\n**Noms commerciaux :** Diamicron® (comprimés), Diamicron® MR (LP)\n\n**Mécanisme d'action**\nSulfonylurée de 2ème génération. Même mécanisme que glibenclamide mais sécrétion insulinique plus physiologique (en réponse à l'hyperglycémie, moins basale) → moins d'hypoglycémies à jeun. Propriétés antioxydantes vasculaires (réduction des radicaux libres).\n\n**Indications principales**\n- Diabète de type 2, en 2ème intention (après metformine)\n- En association avec d'autres antidiabétiques\n\n**Posologie adulte**\n- Diamicron® standard : 80-320 mg/j en 1-2 prises\n- Diamicron® MR : 30-120 mg/j en 1 prise au petit-déjeuner\n\n**Contre-indications**\n- Diabète de type 1, insuffisance rénale ou hépatique sévère, grossesse\n\n**Effets indésirables**\n- Hypoglycémie (moins fréquente que glibenclamide)\n- Prise de poids\n\n**Surveillance infirmière**\n- Glycémie capillaire\n- Form LP : ne pas écraser ni sucer (libération prolongée)\n- Éducation sur l'hypoglycémie`, ['antidiabétique', 'sulfonylurée', 'gliclazide', 'Diamicron', 'DT2', 'hypoglycémie', 'LP']) },

  { classIndex: 8, name: 'Sitagliptine (Januvia®)', genericName: 'Sitagliptine phosphate', description: 'Inhibiteur de la DPP-4 (gliptine). Augmente l\'effet des incrétines (GLP-1 endogène). Hypoglycémies très rares. Neutre sur le poids.',
    ...s(`**DCI :** Sitagliptine phosphate\n**Noms commerciaux :** Januvia®, Xelevia®, Janumet® (sitagliptine + metformine)\n\n**Mécanisme d'action**\nInhibiteur sélectif de la DPP-4 (dipeptidyl peptidase-4), enzyme qui dégrade rapidement les incrétines (GLP-1, GIP). En inhibant la DPP-4 → augmentation du GLP-1 et GIP endogènes → stimulation glucose-dépendante de l'insuline + inhibition du glucagon. Pas d'hypoglycémie en monothérapie (effet glucose-dépendant).\n\n**Indications principales**\n- DT2 en 2ème ou 3ème ligne\n- En association avec metformine, sulfonylurées, insuline\n- Intérêt chez le sujet âgé (peu d'hypoglycémies)\n\n**Posologie adulte**\n- 100 mg/j per os en 1 prise, indépendamment des repas\n- Réduction à 50 mg/j si DFG 30-50 mL/min ; 25 mg/j si DFG < 30\n\n**Contre-indications**\n- Diabète de type 1\n- DFG < 15 mL/min\n\n**Effets indésirables**\n- Nasopharyngites, infections des voies aériennes supérieures\n- Pancréatite aiguë (rare — signal de pharmacovigilance)\n- Arthralgies\n\n**Surveillance infirmière**\n- Surveiller la fonction rénale (adaptation de dose)\n- Informer sur les signes de pancréatite (douleur épigastrique irradiante)\n- Avantage : pas d'hypoglycémie en monothérapie`, ['antidiabétique', 'gliptine', 'DPP-4', 'sitagliptine', 'incrétines', 'DT2', 'pas d\'hypoglycémie']) },

  { classIndex: 8, name: 'Empagliflozine (Jardiance®)', genericName: 'Empagliflozine', description: 'Inhibiteur du SGLT-2 (gliflozine). Réduit la réabsorption rénale du glucose. Bénéfice cardiovasculaire et rénal démontré indépendamment de l\'effet hypoglycémiant.',
    ...s(`**DCI :** Empagliflozine\n**Noms commerciaux :** Jardiance®\n\n**Mécanisme d'action**\nInhibiteur sélectif du co-transporteur sodium-glucose SGLT-2 dans le tubule proximal rénal → blocage de 90% de la réabsorption rénale du glucose → glycosurie et légère diurèse osmotique → baisse de la glycémie, diurèse légèrement augmentée. Perte calorique (70-80g glucose/j dans les urines). Effet natriurétique → légère baisse PA.\n\n**Indications principales**\n- DT2 en association (2ème ou 3ème ligne)\n- Insuffisance cardiaque avec fraction d'éjection réduite (avec ou sans DT2) — étude EMPEROR-Reduced\n- Maladie rénale chronique avec DFG 20-45 (protection rénale) — étude EMPEROR-Preserved\n\n**Posologie adulte**\n- 10 mg/j per os, augmentable à 25 mg/j\n- Indépendamment des repas\n\n**Contre-indications**\n- DFG < 20 mL/min (efficacité nulle)\n- Infections urinaires récidivantes\n- Acidocétose diabétique\n\n**Effets indésirables**\n- Infections génito-urinaires (mycoses vaginales, balanoposthites)\n- Acidocétose euglycémique (rare mais grave)\n- Hypotension orthostatique (diurèse osmotique)\n- Amputations des membres inférieurs (signal classe, surtout canagliflozine)\n\n**Surveillance infirmière**\n- Informer sur le risque d'infections génitales (hygiène intime)\n- Surveiller signes d'acidocétose (nausées, dyspnée, douleur abdominale) même si glycémie normale\n- Arrêt 3j avant chirurgie et situations à risque (jeûne, fièvre, vomissements)`, ['antidiabétique', 'SGLT-2', 'empagliflozine', 'gliflozine', 'IC', 'protection rénale', 'glycosurie']) },

  { classIndex: 8, name: 'Liraglutide (Victoza®)', genericName: 'Liraglutide', description: 'Analogue du GLP-1 injectable, 1 fois/j. Réduit la glycémie, la prise alimentaire et le poids. Bénéfice cardiovasculaire démontré (LEADER trial). Utilisé aussi dans l\'obésité.',
    ...s(`**DCI :** Liraglutide\n**Noms commerciaux :** Victoza® (DT2), Saxenda® (obésité, dose plus élevée)\n\n**Mécanisme d'action**\nAnalogue du GLP-1 (incrétine) à longue durée d'action. Se lie aux récepteurs GLP-1 : stimulation glucose-dépendante de l'insuline, inhibition du glucagon, ralentissement vidange gastrique, satiété centrale. Perte de poids significative. Demi-vie 13h → 1 injection SC/j.\n\n**Indications principales**\n- DT2 en association (Victoza® 1,2-1,8 mg/j)\n- Obésité ou surpoids avec comorbidités (Saxenda® 3 mg/j)\n- Réduction risque CV chez DT2 à haut risque cardiovasculaire\n\n**Posologie adulte**\n- DT2 : initiation 0,6 mg SC/j x 1 semaine, puis 1,2 mg/j, max 1,8 mg/j\n- Injection SC dans abdomen, cuisse ou bras, 1x/j à n'importe quelle heure\n\n**Contre-indications**\n- Antécédents personnels ou familiaux de carcinome médullaire thyroïde (CMT)\n- NEM2 (néoplasie endocrinienne multiple de type 2)\n- Pancréatite aiguë\n\n**Effets indésirables**\n- Nausées, vomissements (fréquents en début — s'atténuent)\n- Pancréatite (rare — signal de pharmacovigilance)\n- Tumeurs thyroïdiennes (signal animal, surveiller la thyroïde)\n\n**Surveillance infirmière**\n- Technique d'injection SC (rotation des sites)\n- Nausées initialement : rassurer (effet transitoire)\n- Surveiller signes de pancréatite\n- Contrôle de la thyroïde`, ['antidiabétique', 'GLP-1', 'liraglutide', 'Victoza', 'incrétine', 'poids', 'cardiovasculaire']) },

  { classIndex: 8, name: 'Insuline glargine (Lantus®)', genericName: 'Insuline glargine', description: 'Insuline analogue basale à action prolongée (24h), sans pic d\'action. Assure le besoin insulinique basal. 1 injection SC/j, à heure fixe.',
    ...s(`**DCI :** Insuline glargine (100 UI/mL ou 300 UI/mL Toujeo®)\n**Noms commerciaux :** Lantus® (100 UI/mL), Toujeo® (300 UI/mL), Abasaglar® (biosimilaire)\n\n**Mécanisme d'action**\nAnalogue de l'insuline humaine. À pH physiologique → précipitation sous-cutanée avec libération lente et régulière sur 24h. Durée d'action 24h pour Lantus®, 36h pour Toujeo®. Pas de pic d'action → profil plus plat que l'insuline NPH → moins d'hypoglycémies nocturnes.\n\n**Indications principales**\n- Diabète de type 1 (besoin basal, associée à insulines rapides)\n- Diabète de type 2 insuffisamment contrôlé par antidiabétiques oraux (insulinothérapie basale)\n\n**Posologie adulte**\n- Adaptation individuelle\n- Départ habituel DT2 : 10 UI SC au coucher (titration sur glycémie à jeun)\n- 1 injection SC/j à heure fixe\n\n**Contre-indications**\n- Hypoglycémie en cours\n- Ne jamais injecter IV (risque d'hypoglycémie sévère)\n\n**Effets indésirables**\n- Hypoglycémie (moins nocturne que NPH)\n- Lipodystrophies au site d'injection\n- Prise de poids\n\n**Surveillance infirmière**\n- NE JAMAIS mélanger dans la même seringue avec une autre insuline (Lantus®)\n- Injection SC dans l'abdomen (ou cuisse, bras)\n- Rotation des sites (prévention lipodystrophies)\n- Glycémie à jeun quotidienne pour titration\n- Conserver au réfrigérateur (stylo non entamé) ; température ambiante ≤ 30°C une fois entamé (max 4 semaines)`, ['insuline', 'basale', 'glargine', 'Lantus', 'DT1', 'DT2', 'analogue', 'longue durée']) },

  { classIndex: 8, name: 'Insuline asparte (Novorapid®)', genericName: 'Insuline asparte', description: 'Insuline analogue rapide (début 10-20 min, pic 1-3h, durée 3-5h). Injectée juste avant le repas. Utilisée comme insuline prandiale dans le DT1 et DT2.',
    ...s(`**DCI :** Insuline asparte\n**Noms commerciaux :** Novorapid®, NovoMix® (asparte biphasique)\n\n**Mécanisme d'action**\nAnalogue rapide de l'insuline humaine (substitution de la proline en position B28 par l'acide aspartique → réduction de l'auto-agrégation → absorption SC plus rapide). Début d'action 10-20 min, pic 1-3h, durée 3-5h → couvre le repas.\n\n**Indications principales**\n- DT1 : insuline prandiale (à chaque repas) en schéma basal-bolus\n- DT2 : insulinothérapie intensive ou simplifiée\n- Diabète gestationnel\n- Pompe à insuline externe\n\n**Posologie adulte**\n- Juste avant le repas (0-10 min avant) ou juste après si glycémie aléatoire\n- Dose selon ratio insuline/glucides et glycémie pré-prandiale (insulinothérapie fonctionnelle)\n\n**Contre-indications**\n- Hypoglycémie en cours\n\n**Effets indésirables**\n- Hypoglycémie (surtout si repas sauté ou insuffisant)\n- Lipodystrophies au site d'injection\n\n**Surveillance infirmière**\n- Glycémie capillaire AVANT injection\n- Ne pas injecter si le patient ne mange pas\n- Rotation des sites d'injection\n- Différencier des insulines basales (étiquettes, stylos — erreur de médicament possible)\n- Si patient NPO (nulla per os) : contacter médecin avant injection d'insuline rapide`, ['insuline', 'rapide', 'asparte', 'Novorapid', 'prandiale', 'DT1', 'analogu', 'bolus']) },

  { classIndex: 8, name: 'Pioglitazone (Actos®)', genericName: 'Pioglitazone chlorhydrate', description: 'Thiazolidinedione (glitazone), insulinosensibilisateur agissant sur les récepteurs PPAR-γ. Améliore la sensibilité à l\'insuline musculaire et hépatique.',
    ...s(`**DCI :** Pioglitazone chlorhydrate\n**Noms commerciaux :** Actos®\n\n**Mécanisme d'action**\nAgoniste des récepteurs PPAR-γ (peroxisome proliferator-activated receptor gamma) → augmentation de l'expression des transporteurs GLUT-4 → amélioration de la captation musculaire et hépatique du glucose → réduction de l'insulinorésistance. Pas de stimulation de l'insulinosécrétion → pas d'hypoglycémie en monothérapie.\n\n**Indications principales**\n- DT2 en 2ème ligne (seul ou en association metformine ou sulfonylurée)\n- Contre-indication ou intolérance à la metformine\n\n**Posologie adulte**\n- 15-45 mg/j per os en 1 prise\n\n**Contre-indications**\n- Insuffisance cardiaque (toute classe NYHA)\n- Antécédent de cancer de la vessie\n- Hématurie macroscopique inexpliquée\n\n**Effets indésirables**\n- Rétention hydrosodée (œdèmes) → risque d'IC\n- Prise de poids\n- Augmentation risque de fractures (femmes ménopausées)\n- Signal de cancer de la vessie (usage > 1 an)\n\n**Surveillance infirmière**\n- Surveiller signes d'insuffisance cardiaque (essoufflement, œdèmes)\n- Surveiller hématurie (cancer de la vessie)\n- Bilan hépatique si anomalie suspectée`, ['antidiabétique', 'pioglitazone', 'PPAR-γ', 'insulinosensibilisateur', 'glitazone', 'DT2', 'IC']) },

  { classIndex: 8, name: 'Acarbose (Glucor®)', genericName: 'Acarbose', description: 'Inhibiteur des alpha-glucosidases intestinales. Ralentit l\'absorption des glucides. Réduction des pics glycémiques post-prandiaux. Pas d\'hypoglycémie en monothérapie.',
    ...s(`**DCI :** Acarbose\n**Noms commerciaux :** Glucor®\n\n**Mécanisme d'action**\nInhibiteur réversible et compétitif des alpha-glucosidases de la bordure en brosse intestinale (maltase, saccharase, glucoamylase) → ralentissement de la digestion et de l'absorption des polysaccharides → réduction des pics glycémiques postprandiaux sans hypoglycémie.\n\n**Indications principales**\n- DT2 (surtout pour contrôle des glycémies post-prandiales)\n- En association avec d'autres antidiabétiques\n- DT1 (en association avec insuline pour réduire les fluctuations post-prandiales)\n\n**Posologie adulte**\n- 50 mg x 3/j au début de chaque repas (comprimés à croquer ou avaler avec 1ère bouchée)\n- Augmentable à 100 mg x 3/j selon tolérance\n\n**Contre-indications**\n- Maladies inflammatoires chroniques de l'intestin, syndrome de malabsorption\n- Hernie abdominale importante\n- Cirrhose hépatique\n\n**Effets indésirables**\n- Flatulences, ballonnements, diarrhées (très fréquents en début — s'atténuent)\n- Douleurs abdominales\n- Élévation des transaminases (doses élevées)\n\n**Surveillance infirmière**\n- Prévenir le patient des flatulences initiales (fréquentes mais transitoires)\n- Éduquer sur la prise avec les repas\n- Si hypoglycémie associée (avec sulfonylurée) : utiliser du glucose pur (saccharose inefficace car absorption bloquée)`, ['antidiabétique', 'acarbose', 'alpha-glucosidase', 'postprandial', 'DT2', 'pas d\'hypoglycémie', 'flatulences']) },
];

/* ══════════════════════════════════════════════════════════════
   CLASSE 9 — Antidépresseurs
══════════════════════════════════════════════════════════════ */

const antidepresseurs = [

  { classIndex: 9, name: 'Sertraline (Zoloft®)', genericName: 'Sertraline chlorhydrate', description: 'ISRS le plus prescrit dans le monde. Bonne tolérance, peu d\'interactions médicamenteuses, safe chez le sujet âgé et en cardiopathie.',
    ...s(`**DCI :** Sertraline chlorhydrate\n**Noms commerciaux :** Zoloft®, Sertraline Mylan®\n\n**Mécanisme d'action**\nInhibiteur sélectif de la recapture de la sérotonine (ISRS). Faibles interactions médicamenteuses (moins inhibiteur des CYP que la fluoxétine). Bien toléré chez le sujet âgé et en cardiopathie.\n\n**Indications principales**\n- Épisode dépressif majeur\n- Trouble panique\n- Trouble obsessionnel compulsif\n- Trouble de stress post-traumatique (TSPT)\n- Trouble anxiété sociale\n\n**Posologie adulte**\n- 50 mg/j le matin, augmentable à 200 mg/j\n- Délai d'action : 2-4 semaines\n\n**Contre-indications**\n- IMAO dans les 14 jours précédents\n- Pimozide\n\n**Effets indésirables**\n- Nausées initiales, insomnie, diarrhées\n- Dysfonction sexuelle\n- Syndrome sérotoninergique (associations)\n- Idées suicidaires en début chez le sujet jeune\n\n**Surveillance infirmière**\n- Évaluation risque suicidaire\n- Natrémie (SIADH surtout sujet âgé)\n- Expliquer le délai d'action (éviter arrêt prématuré)`, ['ISRS', 'sertraline', 'Zoloft', 'antidépresseur', 'dépression', 'TSPT', 'TOC']) },

  { classIndex: 9, name: 'Paroxétine (Déroxat®)', genericName: 'Paroxétine chlorhydrate', description: 'ISRS avec propriétés anticholinergiques supplémentaires. Fort syndrome de discontinuation à l\'arrêt. Actif dans les troubles anxieux.',
    ...s(`**DCI :** Paroxétine chlorhydrate\n**Noms commerciaux :** Déroxat®, Divarius® (LP)\n\n**Mécanisme d'action**\nISRS avec également activité anticholinergique faible et antihistaminique. Inhibiteur puissant du CYP2D6 → nombreuses interactions médicamenteuses. Fort syndrome de discontinuation (courte demi-vie, sans métabolite actif).\n\n**Indications principales**\n- Dépression\n- Trouble panique, TOC\n- Trouble anxiété sociale, anxiété généralisée\n- TSPT\n\n**Posologie adulte**\n- 20 mg/j le matin (repas), augmentable à 60 mg/j\n\n**Contre-indications**\n- IMAO\n- Tamoxifène (interaction CYP2D6 → réduction efficacité anti-cancer du sein)\n\n**Effets indésirables**\n- Syndrome de discontinuation sévère (ne jamais arrêter brutalement)\n- Constipation, sécheresse buccale (effet anticholinergique)\n- Prise de poids\n- Dysfonction sexuelle\n\n**Surveillance infirmière**\n- Décroissance OBLIGATOIRE et progressive (syndrome de sevrage important)\n- Vérifier les interactions (CYP2D6)\n- Évaluation suicidaire`, ['ISRS', 'paroxétine', 'Déroxat', 'antidépresseur', 'discontinuation', 'CYP2D6', 'anxiété']) },

  { classIndex: 9, name: 'Escitalopram (Lexapro®)', genericName: 'Escitalopram oxalate', description: 'ISRS énantiomère actif du citalopram. Très bonne sélectivité sérotoninergique, peu d\'effets secondaires. Bonne tolérance cardiaque.',
    ...s(`**DCI :** Escitalopram oxalate\n**Noms commerciaux :** Seroplex® (France), Lexapro® (international)\n\n**Mécanisme d'action**\nÉnantiomère S du citalopram. ISRS de haute sélectivité. Profil de tolérance favorable. Peu d'interactions médicamenteuses (inhibition CYP2D6 modeste). Association avec l'allongement du QTc à doses élevées → ECG recommandé à 20 mg/j.\n\n**Indications principales**\n- Dépression majeure\n- Trouble panique, TOC\n- Anxiété sociale, anxiété généralisée\n\n**Posologie adulte**\n- 10 mg/j, augmentable à 20 mg/j\n- Maximum 10 mg/j si > 65 ans ou insuffisance hépatique\n\n**Contre-indications**\n- IMAO\n- QT long congénital ou acquis (à surveiller)\n- Associations médicaments allongeant le QT\n\n**Effets indésirables**\n- Nausées, insomnie initiales\n- Allongement QTc (dose-dépendant)\n- Dysfonction sexuelle\n\n**Surveillance infirmière**\n- ECG avant et pendant traitement si ≥ 20 mg/j\n- Évaluation risque suicidaire\n- Surveillance cardiaque chez patients à risque`, ['ISRS', 'escitalopram', 'Seroplex', 'antidépresseur', 'QT long', 'dépression', 'anxiété']) },

  { classIndex: 9, name: 'Citalopram (Séropram®)', genericName: 'Citalopram bromhydrate', description: 'ISRS bien toléré, racémique (escitalopram = énantiomère actif). Surveillance ECG nécessaire à forte dose (allongement QTc dose-dépendant).',
    ...s(`**DCI :** Citalopram bromhydrate (racémique)\n**Noms commerciaux :** Séropram®, Citalopram Mylan®\n\n**Mécanisme d'action**\nISRS racémique (mélange des deux énantiomères R et S). L'énantiomère S (escitalopram) est responsable de l'activité. Bonne sélectivité sérotoninergique. Allongement QTc dose-dépendant (signal réglementaire ANSM 2012 → dose maximale 40 mg/j chez l'adulte, 20 mg si > 60 ans ou insuffisance hépatique).\n\n**Indications principales**\n- Dépression majeure\n- TOC\n\n**Posologie adulte**\n- 20 mg/j, max 40 mg/j (20 mg si > 60 ans, IH, interactions QT)\n\n**Contre-indications**\n- IMAO\n- Médicaments allongeant le QT (contre-indication associée)\n- QT long congénital\n\n**Effets indésirables**\n- Allongement QTc (risque arythmique dose-dépendant)\n- Nausées, insomnie\n- Dysfonction sexuelle\n\n**Surveillance infirmière**\n- ECG (QTc) avant initiation et en cas de dose élevée\n- Respecter strictement la dose maximale\n- Électrolytes (hypokaliémie aggrave le risque QT)`, ['ISRS', 'citalopram', 'Séropram', 'antidépresseur', 'QT long', 'dépression', 'ECG']) },

  { classIndex: 9, name: 'Venlafaxine (Effexor®)', genericName: 'Venlafaxine chlorhydrate', description: 'IRSN (Inhibiteur de la Recapture de la Sérotonine et de la Noradrénaline). Efficace dans la dépression sévère et les douleurs neuropathiques. Surveillane PA (effet noradrénergique).',
    ...s(`**DCI :** Venlafaxine chlorhydrate\n**Noms commerciaux :** Effexor® LP, Venlafaxine Mylan® LP\n\n**Mécanisme d'action**\nIRSN : inhibe à faible dose la recapture de la sérotonine ; à dose plus élevée, inhibe aussi la recapture de la noradrénaline. Cette double action explique l'efficacité sur les douleurs neuropathiques et les bouffées de chaleur (ménopause) en plus de la dépression.\n\n**Indications principales**\n- Dépression majeure (surtout sévère)\n- Trouble anxiété généralisée\n- Trouble panique, phobie sociale\n- Douleurs neuropathiques (hors AMM mais pratique courante)\n- Bouffées de chaleur de la ménopause (hors AMM)\n\n**Posologie adulte**\n- 75 mg LP/j au repas du matin, augmentable à 225-375 mg/j\n\n**Contre-indications**\n- IMAO (absolue)\n- HTA non contrôlée\n\n**Effets indésirables**\n- Élévation de la PA (effet noradrénergique dose-dépendant)\n- Nausées, céphalées, insomnie\n- Syndrome de discontinuation important (demi-vie courte)\n- Tachycardie\n\n**Surveillance infirmière**\n- Mesure PA avant initiation et régulièrement\n- Ne jamais arrêter brutalement (décroissance sur 2-4 semaines)\n- Évaluation suicidaire`, ['IRSN', 'venlafaxine', 'Effexor', 'antidépresseur', 'noradrénaline', 'sérotonine', 'neuropathique', 'PA']) },

  { classIndex: 9, name: 'Duloxétine (Cymbalta®)', genericName: 'Duloxétine chlorhydrate', description: 'IRSN avec effet analgésique central marqué. Indiqué dans la dépression, la neuropathie diabétique douloureuse et la fibromyalgie.',
    ...s(`**DCI :** Duloxétine chlorhydrate\n**Noms commerciaux :** Cymbalta®, Yentreve® (incontinence urinaire), Duloxétine Mylan®\n\n**Mécanisme d'action**\nIRSN équilibré (sérotonine ≈ noradrénaline). L'inhibition de la recapture de la noradrénaline dans les voies descendantes inhibitrices de la douleur → analgésie centrale → efficacité dans les douleurs neuropathiques.\n\n**Indications principales**\n- Dépression majeure\n- Neuropathie diabétique douloureuse\n- Fibromyalgie\n- Anxiété généralisée\n- Incontinence urinaire d'effort (Yentreve®)\n\n**Posologie adulte**\n- 60 mg/j en 1 prise (30 mg/j les 2 premières semaines)\n- Max 120 mg/j\n\n**Contre-indications**\n- IMAO\n- Insuffisance hépatique (métabolisme hépatique étendu)\n- Alcoolisme chronique\n\n**Effets indésirables**\n- Nausées (fréquentes en début)\n- HTA légère\n- Hépatotoxicité (surveillance transaminases)\n- Syndrome de discontinuation\n\n**Surveillance infirmière**\n- Bilan hépatique avant et pendant traitement\n- PA régulière\n- Gélules à avaler entières (ne pas ouvrir)`, ['IRSN', 'duloxétine', 'Cymbalta', 'antidépresseur', 'neuropathie', 'fibromyalgie', 'analgésique']) },

  { classIndex: 9, name: 'Mirtazapine (Norset®)', genericName: 'Mirtazapine', description: 'Antidépresseur NaSSA (Noradrénergique et Sérotoninergique Spécifique). Sédatif, anxiolytique, orexigène. Utile chez les patients dénutris, anxieux ou insomniaques.',
    ...s(`**DCI :** Mirtazapine\n**Noms commerciaux :** Norset®, Mirtazapine Mylan®\n\n**Mécanisme d'action**\nNaSSA : bloque les récepteurs présynaptiques α2-adrénergiques (augmentation libération noradrénaline et sérotonine) + bloque sélectivement les récepteurs 5-HT2 et 5-HT3 (améliore la qualité sérotoninergique → moins d'effets sexuels, moins de nausées). Antihistaminique H1 → sédation et appétit.\n\n**Indications principales**\n- Dépression avec anxiété, insomnie, anorexie\n- Sujet âgé dénutri (stimulation appétit)\n- Quand les effets sexuels des ISRS sont problématiques\n- Nausées sous chimiothérapie (hors AMM — effet anti-5HT3)\n\n**Posologie adulte**\n- 15-45 mg/j le soir au coucher\n\n**Contre-indications**\n- IMAO\n- Agranulocytose préexistante\n\n**Effets indésirables**\n- Sédation importante (surtout faibles doses) → peut être bénéfique le soir\n- Prise de poids, augmentation appétit (souvent recherchée)\n- Agranulocytose (rare — surveiller NFS)\n- Pas de dysfonction sexuelle\n\n**Surveillance infirmière**\n- NFS en cas de fièvre ou infection (signal d'agranulocytose)\n- Évaluer l'appétit et le poids\n- Surveiller la somnolence diurne`, ['antidépresseur', 'mirtazapine', 'NaSSA', 'Norset', 'sédatif', 'orexigène', 'insomnie', 'anxiété']) },

  { classIndex: 9, name: 'Amitriptyline (Laroxyl®)', genericName: 'Amitriptyline chlorhydrate', description: 'Antidépresseur tricyclique (ATC) de référence. Très efficace mais nombreux effets indésirables anticholinergiques et cardiovasculaires. Utilisé aussi en douleurs neuropathiques.',
    ...s(`**DCI :** Amitriptyline chlorhydrate\n**Noms commerciaux :** Laroxyl®, Elavil®\n\n**Mécanisme d'action**\nAntidépresseur tricyclique (ATC) : inhibe la recapture de la noradrénaline et de la sérotonine. Blocage additif des récepteurs muscariniques (anticholinergique), α1-adrénergiques (hypotension) et histaminiques H1 (sédation). Effet analgésique central sur les douleurs neuropathiques (mécanisme noradrénergique).\n\n**Indications principales**\n- Dépression majeure (efficace mais moins bien toléré que les ISRS)\n- Douleurs neuropathiques chroniques (neuropathie diabétique, névralgie post-zostérienne) à faible dose (25-75 mg/j)\n- Fibromyalgie\n- Prévention de la migraine (10-25 mg/j le soir)\n- Traitement de l'énurésie nocturne (enfant)\n\n**Posologie adulte**\n- Dépression : 75-150 mg/j, en 2-3 prises (ou 1 prise le soir si sédatif)\n- Douleurs neuropathiques : 10-75 mg/j le soir\n\n**Contre-indications**\n- IMAO (intervalle de 14 jours obligatoire)\n- Glaucome à angle fermé\n- Adénome prostatique avec rétention\n- Infarctus récent, troubles du rythme\n\n**Effets indésirables**\n- Sécheresse buccale, constipation, rétention urinaire, confusion (effets anticholinergiques)\n- Hypotension orthostatique\n- Allongement QTc, arythmies (surdosage)\n- Sédation importante\n\n**Surveillance infirmière**\n- ECG avant traitement (recherche troubles rythme préexistants)\n- PA couché/debout (hypotension orthostatique)\n- Surveiller la diurèse\n- DANGEREUX en surdosage → ne pas laisser à portée d'un patient suicidaire`, ['antidépresseur', 'tricyclique', 'amitriptyline', 'Laroxyl', 'neuropathique', 'migraine', 'anticholinergique', 'ECG']) },

  { classIndex: 9, name: 'Clomipramine (Anafranil®)', genericName: 'Clomipramine chlorhydrate', description: 'Antidépresseur tricyclique avec forte activité sérotoninergique. Traitement de référence du TOC. Effets indésirables anticholinergiques importants.',
    ...s(`**DCI :** Clomipramine chlorhydrate\n**Noms commerciaux :** Anafranil®\n\n**Mécanisme d'action**\nTricyclique avec prédominance de l'inhibition de la recapture de la sérotonine (le plus sérotoninergique des ATC). Métabolite actif (déméthylclomipramine) → effet noradrénergique supplémentaire. Blocage anticholinergique, antihistaminique et anti-α1. Référence thérapeutique dans le TOC (efficacité supérieure aux ISRS dans certaines études).\n\n**Indications principales**\n- Trouble obsessionnel compulsif (TOC) — traitement de référence\n- Dépression\n- Phobies, anxiété, trouble panique\n- Cataplexie liée à la narcolepsie\n- Énurésie nocturne (enfant)\n\n**Posologie adulte**\n- TOC : 75-300 mg/j en doses fractionnées\n- Dépression : 75-150 mg/j\n\n**Contre-indications**\n- IMAO\n- Infarctus récent, troubles du rythme\n- Glaucome à angle fermé, adénome prostatique\n\n**Effets indésirables**\n- Effets anticholinergiques sévères (sécheresse buccale, constipation, rétention urinaire)\n- Sédation importante\n- Allongement QTc, risque arythmie\n- Hypotension orthostatique\n- Convulsions (doses élevées)\n\n**Surveillance infirmière**\n- ECG (QTc) avant et pendant traitement\n- Surveillance de la constipation (prévention par régime, laxatifs)\n- PA orthostatique\n- Sécuriser la prescription (risque de surdosage chez patients déprimés)`, ['antidépresseur', 'tricyclique', 'clomipramine', 'Anafranil', 'TOC', 'sérotonine', 'anticholinergique', 'ECG']) },
];

module.exports = { diuretiques, benzodiazepines, antidiabetiques, antidepresseurs };
