/**
 * seedMed_p1.js — 30 médicaments
 * Classe 0 : Antibiotiques — Pénicillines (drogues 2-10)
 * Classe 1 : AINS (drogues 2-10)
 * Classe 2 : Analgésiques — Antipyrétiques (drogues 2-10)
 */

function s(general, tags) {
  return {
    sections: [
      { title: 'Général', content: general, order: 0 },
      { title: 'Médias',  content: 'Schémas et ressources pédagogiques disponibles dans les supports de cours IFSI et sur le site de l\'ANSM.', order: 1 },
      { title: 'Source',  content: '**Références**\n1. ANSM — Monographie du médicament. [ansm.sante.fr]\n2. Vidal — Fiche médicament. [vidal.fr]\n3. HAS — Recommandations de bon usage. [has-sante.fr]\n4. Société savante de référence — Recommandations cliniques.', order: 2 },
    ],
    sources: [
      { title: 'ANSM — Monographie', authors: 'ANSM', year: '2023', url: 'https://ansm.sante.fr' },
      { title: 'Vidal',              authors: 'Vidal', year: '2023', url: 'https://vidal.fr' },
    ],
    tags,
  };
}

/* ══════════════════════════════════════════════════════════════
   CLASSE 0 — Antibiotiques — Pénicillines
══════════════════════════════════════════════════════════════ */

const antibiotiques = [

  { classIndex: 0, name: 'Ampicilline (Totapen®)', genericName: 'Ampicilline', description: 'Pénicilline A à large spectre, active sur les bacilles à Gram négatif et les entérocoques. Utilisée notamment en néonatologie et pour les méningites.',
    ...s(`**DCI :** Ampicilline\n**Noms commerciaux :** Totapen®\n\n**Mécanisme d'action**\nBêta-lactamine bactéricide : inhibe la synthèse de la paroi bactérienne en se liant aux PLP (protéines liant les pénicillines). Spectre élargi aux entérobactéries sensibles et aux entérocoques.\n\n**Indications principales**\n- Méningites bactériennes (Listeria, méningocoques, en association)\n- Infections à Enterococcus faecalis (endocardites, en association avec aminoside)\n- Infections ORL, respiratoires, urinaires à germes sensibles\n- Péri-opératoire (prophylaxie chirurgicale dans certains contextes)\n- Néonatologie : infections bactériennes du nouveau-né\n\n**Posologie adulte**\n- Per os : 500 mg à 1 g x 3-4/j\n- IV : 1 à 2 g x 4-6/j selon gravité (jusqu'à 12 g/j en méningite)\n- Perfusion IV en 30-60 min\n\n**Voies d'administration :** Orale (gélules), IV directe, IM\n\n**Contre-indications**\n- Allergie aux pénicillines (absolue)\n- Mononucléose infectieuse (rash maculopapuleux)\n\n**Effets indésirables**\n- Troubles digestifs (nausées, diarrhées)\n- Éruptions cutanées (fréquentes, surtout si MNI)\n- Choc anaphylactique (rare)\n- Colite à C. difficile (traitement prolongé)\n\n**Surveillance infirmière**\n- Interrogatoire allergique avant administration\n- Matériel d'urgence anaphylactique disponible\n- En IV : compatibilité avec le soluté de dilution (instable en glucose)\n- Surveiller apparition de rash cutané`, ['antibiotique', 'pénicilline', 'bêta-lactamine', 'méningite', 'entérocoque']) },

  { classIndex: 0, name: 'Amoxicilline/Acide clavulanique (Augmentin®)', genericName: 'Amoxicilline + Acide clavulanique', description: 'Association d\'une pénicilline A et d\'un inhibiteur de bêta-lactamase. Élargit le spectre de l\'amoxicilline aux souches productrices de bêta-lactamases.',
    ...s(`**DCI :** Amoxicilline trihydrate / Clavulanate de potassium\n**Noms commerciaux :** Augmentin®, Ciblor®\n\n**Mécanisme d'action**\nL'acide clavulanique inhibe de manière irréversible les bêta-lactamases bactériennes, protégeant l'amoxicilline de la dégradation enzymatique. Spectre élargi : entérobactéries, Staphylococcus aureus méti-S, anaérobies.\n\n**Indications principales**\n- Infections ORL de l'adulte et de l'enfant (otites, sinusites, angines à risque)\n- Infections respiratoires basses (pneumonies communautaires)\n- Infections cutanées et des tissus mous (morsures animales +++)\n- Infections urinaires (cystites récidivantes, pyélonéphrites)\n- Infections dentaires et péri-apicales\n- Infections gynécologiques et pelviennes\n\n**Posologie adulte**\n- Per os : 1 g (875 mg/125 mg) x 2-3/j selon infection\n- IV : 1 g x 3/j (jusqu'à 6 g/j en infection sévère)\n- Durée : 5 à 14 jours selon indication\n\n**Voies d'administration :** Orale (comprimés 500/62,5 mg et 1 g/125 mg, suspension), IV\n\n**Contre-indications**\n- Allergie aux pénicillines ou aux céphalosporines\n- ATCD d'ictère/hépatite induit par l'association amoxicilline/clavulanate\n- Mononucléose infectieuse\n\n**Effets indésirables**\n- Troubles digestifs fréquents (prendre au début du repas)\n- Hépatite cytolytique (surtout avec le clavulanate)\n- Éruptions cutanées\n- Candidoses digestives ou vaginales\n\n**Surveillance infirmière**\n- Toujours prendre avec de la nourriture (meilleure tolérance digestive)\n- Surveiller signes d'hépatotoxicité : ictère, urines foncées, asthénie\n- En IV : dilution dans NaCl 0,9 % (incompatible avec glucose)\n- Contrôle bilan hépatique si traitement prolongé`, ['antibiotique', 'pénicilline', 'inhibiteur bêta-lactamase', 'amoxicilline', 'clavulanate', 'morsures']) },

  { classIndex: 0, name: 'Pipéracilline/Tazobactam (Tazocilline®)', genericName: 'Pipéracilline + Tazobactam', description: 'Uréidopénicilline associée à un inhibiteur de bêta-lactamase. Antibiotique à très large spectre, réservé à l\'usage hospitalier pour infections sévères.',
    ...s(`**DCI :** Pipéracilline sodique / Tazobactam sodique\n**Noms commerciaux :** Tazocilline®, Tazobac®\n\n**Mécanisme d'action**\nLa pipéracilline est une uréidopénicilline active contre Pseudomonas aeruginosa. Le tazobactam inhibe les bêta-lactamases de classe A et C. Association bactéricide à très large spectre (Gram+, Gram-, anaérobies, Pseudomonas).\n\n**Indications principales**\n- Infections sévères nosocomiales (pneumopathies acquises sous ventilation, bactériémies)\n- Infections intra-abdominales compliquées (péritonites)\n- Infections urinaires compliquées (pyélonéphrites sur obstacle)\n- Infections de la peau et des tissus mous graves\n- Neutropénie fébrile (en association)\n- Infections à Pseudomonas aeruginosa\n\n**Posologie adulte**\n- IV : 4 g/0,5 g x 3-4/j en perfusion de 30 min à 4 h selon protocole\n- En IVSE (perfusion continue) dans certains services\n- Adaptation nécessaire si insuffisance rénale\n\n**Voies d'administration :** IV exclusivement (usage hospitalier)\n\n**Contre-indications**\n- Allergie aux pénicillines\n- Allergie aux céphalosporines (précaution)\n\n**Effets indésirables**\n- Troubles digestifs, diarrhées\n- Réactions allergiques\n- Hypokaliémie (contenu sodique élevé)\n- Élévation transitoire des transaminases\n- Colite à C. difficile\n\n**Surveillance infirmière**\n- Réservé à l'hôpital : vérifier la voie veineuse avant perfusion\n- Surveiller kaliémie (effet hypo-kaliémiant)\n- Ne pas mélanger avec d'autres antibiotiques dans la même perfusion\n- Durée de perfusion respectée (efficacité dépendante du temps)`, ['antibiotique', 'pénicilline', 'Pseudomonas', 'nosocomial', 'tazobactam', 'pipéracilline', 'large spectre']) },

  { classIndex: 0, name: 'Oxacilline (Bristopen®)', genericName: 'Oxacilline', description: 'Pénicilline M résistante aux pénicillinases staphylococciques. Traitement de référence des infections à Staphylococcus aureus méticillino-sensible (SAMS).',
    ...s(`**DCI :** Oxacilline\n**Noms commerciaux :** Bristopen®\n\n**Mécanisme d'action**\nPénicilline M (isoxazolylpénicilline) stable aux bêta-lactamases staphylococciques grâce à sa chaîne latérale encombrée. Bactéricide sur les SAMS et les streptocoques. Inactive sur les SAMR (Staphylococcus aureus résistant à la méticilline).\n\n**Indications principales**\n- Infections à SAMS : endocardites infectieuses (traitement de référence)\n- Infections ostéo-articulaires (ostéomyélites, arthrites septiques)\n- Infections de la peau et des tissus mous graves à SAMS\n- Pneumonies à SAMS\n- Bactériémies à SAMS\n\n**Posologie adulte**\n- IV : 8 à 12 g/j en 4-6 perfusions de 30-60 min (endocardites)\n- IM : 500 mg à 1 g x 4/j (infections moins sévères)\n- Durée variable : 4-6 semaines pour endocardites\n\n**Voies d'administration :** IV (usage hospitalier surtout), IM\n\n**Contre-indications**\n- Allergie aux pénicillines\n- Allergie sévère aux céphalosporines\n\n**Effets indésirables**\n- Hépatotoxicité (hausse transaminases) — surveillance obligatoire\n- Troubles digestifs\n- Phlébite sur voie veineuse périphérique (irritant)\n- Néphrite interstitielle (rare)\n\n**Surveillance infirmière**\n- Bilan hépatique (ASAT, ALAT) avant et pendant traitement\n- Voie veineuse centrale recommandée pour les cures prolongées (irritation veineuse)\n- Respecter les intervalles de perfusion (bêta-lactamine temps-dépendante)\n- Surveiller signes de phlébite`, ['antibiotique', 'pénicilline M', 'SAMS', 'staphylocoque', 'endocardite', 'ostéomyélite']) },

  { classIndex: 0, name: 'Pénicilline G (Pénicilline G Panpharma®)', genericName: 'Benzylpénicilline sodique', description: 'Première pénicilline découverte, bactéricide à spectre étroit. Traitement de référence des infections à streptocoques, pneumocoques sensibles et spirochètes.',
    ...s(`**DCI :** Benzylpénicilline sodique (Pénicilline G)\n**Noms commerciaux :** Pénicilline G Panpharma®\n\n**Mécanisme d'action**\nBêta-lactamine bactéricide à spectre étroit. Très active sur les cocci Gram+ (streptocoques, pneumocoques de sensibilité intermédiaire), les spirochètes (Treponema pallidum), Clostridium, et Actinomyces. Détruite par les bêta-lactamases.\n\n**Indications principales**\n- Syphilis (traitement de référence à tous stades)\n- Angine streptococcique (alternative à l'amoxicilline)\n- Pneumococcies sensibles (méningites, pneumonies)\n- Endocardites à streptocoques oraux\n- Gangrène gazeuse (C. perfringens)\n- Actinomycose\n\n**Posologie adulte**\n- IM : 1 à 4 M UI x 4-6/j\n- IV : 12 à 24 M UI/j en perfusion continue ou discontinue (infections graves)\n- Syphilis primaire : benzathine pénicilline G 2,4 M UI IM dose unique\n\n**Voies d'administration :** IM, IV (jamais intrarachidienne)\n\n**Contre-indications**\n- Allergie aux pénicillines\n- Injection intrarachidienne (risque d'épilepsie)\n\n**Effets indésirables**\n- Réactions allergiques (urticaire, choc anaphylactique)\n- Encéphalopathie aux pénicillines (fortes doses IV)\n- Électrolytes : apport sodique élevé à fortes doses (Na+ dans la formulation)\n\n**Surveillance infirmière**\n- Test d'allergie avant injection IM si possible\n- Injection IM lente et profonde (quadrant supéro-externe de la fesse)\n- Surveillance 30 min après injection (risque anaphylaxie)\n- À fortes doses IV : surveiller natrémie et bilan rénal`, ['antibiotique', 'pénicilline G', 'syphilis', 'streptocoque', 'pneumocoque', 'bêta-lactamine']) },

  { classIndex: 0, name: 'Pénicilline V (Oracilline®)', genericName: 'Phénoxyméthylpénicilline', description: 'Pénicilline orale acido-résistante, forme per os de la pénicilline G. Utilisée pour les prophylaxies et les infections ORL légères à streptocoques.',
    ...s(`**DCI :** Phénoxyméthylpénicilline (Pénicilline V)\n**Noms commerciaux :** Oracilline®\n\n**Mécanisme d'action**\nMême mécanisme que la pénicilline G mais acido-résistante permettant l'administration orale. Spectre étroit : streptocoques du groupe A, pneumocoques sensibles. Détruite par les bêta-lactamases.\n\n**Indications principales**\n- Prophylaxie des récidives de RAA (rhumatisme articulaire aigu)\n- Prophylaxie des infections à pneumocoque (asplénie fonctionnelle ou anatomique)\n- Angines streptococciques (alternative à l'amoxicilline chez l'enfant)\n- Prévention de l'érysipèle récidivant\n- Traitement de la scarlatine\n\n**Posologie adulte**\n- Traitement : 1 M UI x 3/j per os\n- Prophylaxie RAA : 1 à 2 M UI/j pendant au minimum 10 ans (ou jusqu'à l'âge adulte)\n- Prophylaxie asplénie : 2 M UI/j à vie\n\n**Voies d'administration :** Orale uniquement (comprimés 1 M UI)\n\n**Contre-indications**\n- Allergie aux pénicillines\n\n**Effets indésirables**\n- Troubles digestifs légers\n- Éruptions cutanées (rares)\n- Réactions allergiques\n\n**Surveillance infirmière**\n- Éducation sur la prise régulière (prophylaxie au long cours)\n- Insister sur l'importance de ne pas arrêter la prophylaxie sans avis médical\n- Prendre à distance des repas si possible (absorption légèrement réduite par la nourriture)`, ['antibiotique', 'pénicilline V', 'prophylaxie', 'RAA', 'streptocoque', 'asplénie']) },

  { classIndex: 0, name: 'Flucloxacilline (Floxapen®)', genericName: 'Flucloxacilline', description: 'Isoxazolylpénicilline orale résistante aux pénicillinases. Active sur les SAMS. Utilisée en relais per os des infections staphylococciques traitées initialement par oxacilline IV.',
    ...s(`**DCI :** Flucloxacilline\n**Noms commerciaux :** Floxapen®\n\n**Mécanisme d'action**\nMême classe que l'oxacilline (pénicilline M) mais disponible en forme orale. Résistante aux bêta-lactamases staphylococciques. Bactéricide sur SAMS et streptocoques.\n\n**Indications principales**\n- Relais per os des infections à SAMS après traitement IV par oxacilline\n- Impétigo bulleux à SAMS\n- Furoncles, anthrax, cellulites à SAMS\n- Ostéomyélites chroniques (relais oral)\n- Infections de plaie post-opératoire à SAMS\n\n**Posologie adulte**\n- 500 mg à 1 g x 4/j per os, à jeun (absorption réduite par les aliments)\n- Durée selon indication : 5 à 21 jours ou plus\n\n**Voies d'administration :** Orale (gélules, suspension)\n\n**Contre-indications**\n- Allergie aux pénicillines\n- Insuffisance hépatique sévère\n\n**Effets indésirables**\n- Troubles digestifs (prendre à jeun, 30 min avant les repas)\n- Hépatotoxicité (élévation transaminases, cholestase) — à surveiller\n- Éruptions cutanées\n\n**Surveillance infirmière**\n- Prendre IMPÉRATIVEMENT à jeun (au moins 30 min avant le repas)\n- Bilan hépatique régulier si traitement long\n- Éduquer sur les signes d'ictère`, ['antibiotique', 'pénicilline M', 'SAMS', 'staphylocoque', 'relais oral', 'flucloxacilline']) },

  { classIndex: 0, name: 'Benzathine benzylpénicilline (Extencilline®)', genericName: 'Benzathine benzylpénicilline', description: 'Forme retard de la pénicilline G à libération prolongée. Injection IM unique ou mensuelle. Traitement de référence de la syphilis et prophylaxie du RAA.',
    ...s(`**DCI :** Benzathine benzylpénicilline\n**Noms commerciaux :** Extencilline®\n\n**Mécanisme d'action**\nSel peu soluble de la pénicilline G qui se libère lentement après injection IM, maintenant des concentrations thérapeutiques pendant 2 à 4 semaines. Bactéricide sur les streptocoques et Treponema pallidum.\n\n**Indications principales**\n- Syphilis précoce (primaire, secondaire) : injection unique de 2,4 M UI IM\n- Syphilis tardive : 3 injections à 1 semaine d'intervalle\n- Prophylaxie au long cours du RAA (rhumatisme articulaire aigu)\n- Angine streptococcique (dose unique possible)\n\n**Posologie adulte**\n- Syphilis : 2,4 M UI IM dose unique (syphilis précoce) ou x3 à J1-J8-J15 (tardive)\n- Prophylaxie RAA : 2,4 M UI IM toutes les 3-4 semaines\n\n**Voies d'administration :** IM exclusivement — JAMAIS IV (risque fatal)\n\n**Contre-indications**\n- Allergie aux pénicillines\n- Administration IV (ABSOLUE — risque d'embolie, de mort)\n\n**Effets indésirables**\n- Douleur au site d'injection (formule huileuse)\n- Réaction de Jarisch-Herxheimer (syphilis : fièvre, frissons dans les 24h)\n- Choc anaphylactique\n\n**Surveillance infirmière**\n- VÉRIFIER impérativement la voie IM (jamais IV)\n- Injection profonde dans le muscle, biseau inséré entier\n- Aspiration avant injection pour vérifier l'absence de retour sanguin\n- Surveiller au moins 30 min après injection (anaphylaxie)\n- Prévenir le patient de la réaction de Jarisch-Herxheimer`, ['pénicilline G', 'retard', 'syphilis', 'RAA', 'prophylaxie', 'IM', 'Jarisch-Herxheimer']) },

  { classIndex: 0, name: 'Ticarcilline/Acide clavulanique (Claventin®)', genericName: 'Ticarcilline + Acide clavulanique', description: 'Carboxypénicilline associée à un inhibiteur de bêta-lactamase. Usage hospitalier pour infections sévères à bacilles Gram négatif dont Pseudomonas.',
    ...s(`**DCI :** Ticarcilline disodique / Acide clavulanique\n**Noms commerciaux :** Claventin®\n\n**Mécanisme d'action**\nLa ticarcilline est une carboxypénicilline active contre Pseudomonas aeruginosa. L'acide clavulanique étend son spectre aux souches productrices de bêta-lactamases. Bactéricide large spectre : entérobactéries, Pseudomonas, anaérobies, SAMS.\n\n**Indications principales**\n- Infections nosocomiales sévères à bacilles Gram négatif\n- Infections à Pseudomonas aeruginosa (en association avec un aminoside en cas de gravité)\n- Péritonites secondaires et infections intra-abdominales\n- Infections urinaires hautes compliquées\n- Bactériémies en milieu hospitalier\n\n**Posologie adulte**\n- IV : 3 g (ticarcilline 3 g + clavulanate 200 mg) x 4-6/j\n- Perfusion en 30-60 min\n- Adaptation de dose en cas d'insuffisance rénale\n\n**Voies d'administration :** IV uniquement (usage hospitalier)\n\n**Contre-indications**\n- Allergie aux pénicillines\n- Allergie aux céphalosporines (précaution)\n\n**Effets indésirables**\n- Hypokaliémie (apport sodique élevé dans la formule)\n- Troubles digestifs\n- Allongement du temps de saignement\n- Phlébite sur voie veineuse périphérique\n\n**Surveillance infirmière**\n- Bilan ionique (kaliémie, natrémie) régulier\n- Voie centrale préférée pour traitements prolongés\n- Ne pas mélanger avec d'autres médicaments dans la perfusion`, ['antibiotique', 'pénicilline', 'ticarcilline', 'Pseudomonas', 'nosocomial', 'large spectre', 'clavulanate']) },
];

/* ══════════════════════════════════════════════════════════════
   CLASSE 1 — Anti-inflammatoires non stéroïdiens (AINS)
══════════════════════════════════════════════════════════════ */

const ains = [

  { classIndex: 1, name: 'Kétoprofène (Profénid®)', genericName: 'Kétoprofène', description: 'AINS dérivé de l\'acide propionique, disponible par voies orale, IV et locale. Très utilisé en rhumatologie et en post-opératoire.',
    ...s(`**DCI :** Kétoprofène\n**Noms commerciaux :** Profénid®, Bi-Profénid® (LP), Kétoprofène Mylan®\n\n**Mécanisme d'action**\nInhibiteur non sélectif des COX-1 et COX-2. Bonne pénétration articulaire. La forme IV est utilisée en post-opératoire en analgésie multimodale.\n\n**Indications principales**\n- Poussées douloureuses d'arthrose, arthrite rhumatoïde\n- Spondylarthrite ankylosante\n- Dysménorrhées\n- Douleurs post-opératoires (IV)\n- Coliques néphréthiques (IV, en urgence)\n- Traumatismes musculo-squelettiques\n\n**Posologie adulte**\n- Per os : 100 à 200 mg/j en 2-3 prises (pendant repas)\n- IV : 100 mg en perfusion de 20 min, 3-4 fois/j\n- LP oral : 200 mg/j en 1 prise\n\n**Contre-indications**\n- Ulcère gastroduodénal évolutif, antécédents d'hémorragie digestive sous AINS\n- Grossesse > 24 SA (fœtotoxicité)\n- Insuffisance rénale, hépatique ou cardiaque sévère\n- Asthme à l'aspirine\n\n**Effets indésirables**\n- Troubles digestifs fréquents (épigastralgies, nausées)\n- Risque ulcère/hémorragie digestive (surtout si âge > 65 ans, antécédents)\n- Rétention hydrosodée, HTA\n- Photosensibilisation cutanée (forme locale)\n\n**Surveillance infirmière**\n- Toujours avec la nourriture\n- Associer IPP si risque digestif élevé\n- Surveiller TA, diurèse, signes digestifs\n- En IV : surveillance de la tolérance veineuse`, ['AINS', 'kétoprofène', 'antalgique', 'anti-inflammatoire', 'colique néphrétique', 'post-opératoire']) },

  { classIndex: 1, name: 'Diclofénac (Voltarène®)', genericName: 'Diclofénac', description: 'AINS dérivé de l\'acide phénylacétique, à légère préférence COX-2. Disponible en de nombreuses formes galéniques. L\'une des molécules AINS les plus utilisées dans le monde.',
    ...s(`**DCI :** Diclofénac\n**Noms commerciaux :** Voltarène®, Voltarène Emulgel® (topique), Diclofénac Mylan®\n\n**Mécanisme d'action**\nInhibiteur non sélectif des COX-1/COX-2 avec légère préférence pour COX-2. Bonne biodisponibilité orale et pénétration synoviale. Excellent rapport efficacité/tolérance digestive comparé à d'autres AINS.\n\n**Indications principales**\n- Arthrose, polyarthrite rhumatoïde, spondylarthrite\n- Douleurs post-traumatiques\n- Dysménorrhées\n- Migraines (forme orale)\n- Douleurs post-opératoires\n- Kératite actinique, inflammation oculaire (forme ophtalmique)\n\n**Posologie adulte**\n- Per os : 75 à 150 mg/j en 2-3 prises avec repas\n- LP : 75-100 mg x 1-2/j\n- Topique (gel) : 3 à 4 applications/j sur zone douloureuse\n\n**Contre-indications**\n- Mêmes que les autres AINS\n- Insuffisance cardiaque congestive (risque cardiovasculaire accru en comparaison aux autres AINS)\n\n**Effets indésirables**\n- Gastroduodénal (ulcère, hémorragie)\n- Risque cardiovasculaire légèrement plus élevé que l'ibuprofène\n- Élévation des transaminases (surveillance hépatique recommandée)\n- Photosensibilité (forme topique)\n\n**Surveillance infirmière**\n- Bilan hépatique si traitement prolongé\n- Associer IPP si risque digestif\n- Prévenir le patient du risque cardiovasculaire`, ['AINS', 'diclofénac', 'Voltarène', 'anti-inflammatoire', 'arthrose', 'COX-2']) },

  { classIndex: 1, name: 'Naproxène (Naprosyne®)', genericName: 'Naproxène', description: 'AINS à longue demi-vie (12-17h) permettant 2 prises par jour. Disponible sans ordonnance à faible dose. Demi-vie longue offrant un confort de prise.',
    ...s(`**DCI :** Naproxène\n**Noms commerciaux :** Naprosyne®, Apranax®, Alève® (automédication)\n\n**Mécanisme d'action**\nInhibiteur non sélectif des COX-1/COX-2. Demi-vie longue (12-17 h) autorisant 2 prises/j. Bonne biodisponibilité orale.\n\n**Indications principales**\n- Arthrose, polyarthrite rhumatoïde\n- Goutte aiguë\n- Dysménorrhées (efficacité supérieure à d'autres AINS sur les crampes utérines)\n- Douleurs musculo-squelettiques\n- Céphalées de tension, migraines légères\n\n**Posologie adulte**\n- 500 mg x 2/j per os (500-1 100 mg/j selon indication)\n- Automédication : 220 mg toutes les 8-12 h (max 660 mg/j)\n- Prendre avec un verre d'eau et de la nourriture\n\n**Contre-indications**\n- Ulcère gastroduodénal évolutif\n- Grossesse > 24 SA\n- Insuffisance rénale ou hépatique sévère\n- Asthme à l'aspirine\n\n**Effets indésirables**\n- Troubles digestifs\n- Rétention hydrosodée, œdèmes\n- Risque cardiovasculaire (usage prolongé)\n- Éruptions cutanées\n\n**Surveillance infirmière**\n- Espacer les prises (demi-vie longue → risque d'accumulation)\n- Surveillance TA et prise de poids (rétention sodée)\n- Surveiller créatinine si risque rénal`, ['AINS', 'naproxène', 'anti-inflammatoire', 'dysmémorrhée', 'longue demi-vie', 'arthrose']) },

  { classIndex: 1, name: 'Indométacine (Indocid®)', genericName: 'Indométacine', description: 'AINS dérivé de l\'acide indolacétique, puissant mais moins bien toléré que les autres AINS. Traitement de référence de la crise de goutte aiguë et de la péricardite.',
    ...s(`**DCI :** Indométacine\n**Noms commerciaux :** Indocid®\n\n**Mécanisme d'action**\nInhibiteur puissant et non sélectif des COX-1/COX-2. L'un des AINS les plus puissants. Également inhibiteur de la migration des polynucléaires neutrophiles (effet anti-inflammatoire renforcé). Effet anti-uricosurique.\n\n**Indications principales**\n- Crise de goutte aiguë (traitement de référence avec colchicine)\n- Péricardite aiguë (en association avec colchicine)\n- Fermeture du canal artériel chez le prématuré (IV pédiatrique)\n- Poussées de spondylarthrite ankylosante\n- Ostéome ostéoïde (traitement antalgique)\n\n**Posologie adulte**\n- Goutte : 75-150 mg/j en 3 prises pendant 5-7 j\n- Péricardite : 75-150 mg/j en 3 prises (décroissance sur 2-4 semaines)\n- Prendre avec nourriture ou lait\n\n**Contre-indications**\n- Ulcère gastroduodénal évolutif (risque hémorragique élevé)\n- Grossesse > 24 SA\n- Insuffisances rénale, hépatique, cardiaque sévères\n- Antécédents de troubles psychiatriques sévères\n\n**Effets indésirables**\n- Troubles digestifs fréquents et sévères (nausées, ulcères)\n- Céphalées, vertiges (effets neuropsychiatriques)\n- Rétention hydrosodée\n- Risque cardiovasculaire élevé\n\n**Surveillance infirmière**\n- Traitement de courte durée si possible\n- IPP systématique recommandé\n- Surveiller signes neurologiques (céphalées, confusion)\n- À prendre impérativement avec les repas`, ['AINS', 'indométacine', 'goutte', 'péricardite', 'anti-inflammatoire puissant', 'COX']) },

  { classIndex: 1, name: 'Méloxicam (Mobic®)', genericName: 'Méloxicam', description: 'AINS préférentiel COX-2, dit « anti-COX-2 partiel ». Meilleure tolérance gastrique que les AINS classiques tout en conservant une bonne efficacité anti-inflammatoire.',
    ...s(`**DCI :** Méloxicam\n**Noms commerciaux :** Mobic®, Méloxicam Mylan®\n\n**Mécanisme d'action**\nInhibiteur préférentiel de la COX-2 (sélectivité partielle). Réduit la synthèse des prostaglandines pro-inflammatoires avec un moindre impact sur la muqueuse gastrique (COX-1) comparé aux AINS classiques. Longue demi-vie (20 h) → 1 prise/j.\n\n**Indications principales**\n- Symptômes d'arthrose (notamment hanche, genou)\n- Polyarthrite rhumatoïde (traitement symptomatique)\n- Spondylarthrite ankylosante\n\n**Posologie adulte**\n- Arthrose : 7,5 mg/j per os (augmentable à 15 mg si nécessaire)\n- PR/SPA : 15 mg/j per os\n- 1 prise quotidienne avec le repas\n\n**Contre-indications**\n- Mêmes que les AINS classiques (ulcère, grossesse > 24 SA, IR sévère)\n- Insuffisance cardiaque (risque cardiovasculaire)\n\n**Effets indésirables**\n- Meilleure tolérance gastrique que les AINS non sélectifs mais risque ulcère non nul\n- Rétention hydrosodée, HTA\n- Risque cardiovasculaire (surtout dose 15 mg)\n\n**Surveillance infirmière**\n- 1 seule prise par jour (demi-vie longue)\n- IPP si facteurs de risque digestifs\n- Surveiller TA et bilan rénal si usage prolongé`, ['AINS', 'méloxicam', 'COX-2', 'arthrose', 'rhumatologie', '1 prise par jour']) },

  { classIndex: 1, name: 'Célécoxib (Celebrex®)', genericName: 'Célécoxib', description: 'Coxib, inhibiteur sélectif de la COX-2. Meilleure tolérance gastro-intestinale que les AINS classiques mais risque cardiovasculaire accru. Réservé aux patients à risque digestif élevé.',
    ...s(`**DCI :** Célécoxib\n**Noms commerciaux :** Celebrex®\n\n**Mécanisme d'action**\nInhibiteur hautement sélectif de la COX-2, sans effet significatif sur la COX-1 muqueuse gastrique. Réduit fortement le risque d'ulcère gastroduodénal. Ne possède pas d'effet antiagrégant plaquettaire (absence d'inhibition du thromboxane A2).\n\n**Indications principales**\n- Symptômes d'arthrose chez patients à risque élevé d'ulcère gastroduodénal\n- Polyarthrite rhumatoïde\n- Spondylarthrite ankylosante\n\n**Posologie adulte**\n- 100 à 200 mg x 2/j per os (selon indication)\n- Prendre avec ou sans nourriture\n\n**Contre-indications**\n- Cardiopathie ischémique, AVC, artérite (risque cardiovasculaire accru)\n- Grossesse > 24 SA\n- Insuffisance hépatique sévère (métabolisme CYP2C9)\n- Allergie aux sulfamides\n\n**Effets indésirables**\n- Risque cardiovasculaire augmenté (thromboses artérielles)\n- Rétention hydrosodée, HTA\n- Troubles digestifs (moins fréquents qu'avec AINS classiques)\n\n**Surveillance infirmière**\n- Réservé aux patients à risque digestif élevé (pas pour tous)\n- Surveiller TA et signes cardiovasculaires\n- Ne pas associer avec aspirine (perd le bénéfice digestif)`, ['AINS', 'célécoxib', 'coxib', 'COX-2 sélectif', 'cardiovasculaire', 'gastroprotection']) },

  { classIndex: 1, name: 'Acide acétylsalicylique (Aspégic®)', genericName: 'Acide acétylsalicylique', description: 'Salicylé le plus ancien. À dose anti-inflammatoire (> 2 g/j) : AINS. À dose antiagrégante (75-325 mg/j) : prévention cardiovasculaire. À dose antipyrétique (500 mg-1 g/j) : analgésique.',
    ...s(`**DCI :** Acide acétylsalicylique (AAS)\n**Noms commerciaux :** Aspégic®, Aspirine UPSA®, Kardégic® (antiagrégant)\n\n**Mécanisme d'action**\nInhibition irréversible et non sélective des COX-1 et COX-2 par acétylation. À forte dose : effet anti-inflammatoire. À faible dose : inhibition irréversible de la thromboxane A2 plaquettaire (antiagrégant plaquettaire irréversible sur toute la durée de vie des plaquettes = 7-10 j).\n\n**Indications principales**\n- Antiagrégant : prévention secondaire des événements cardiovasculaires (IDM, AVC ischémique)\n- Anti-inflammatoire (doses > 2 g/j) : rhumatismes\n- Antipyrétique/antalgique : fièvre, douleurs légères\n- Maladie de Kawasaki (pédiatrie)\n\n**Posologie adulte**\n- Antiagrégant : 75-100 mg/j (Kardégic®)\n- Antipyrétique : 500 mg-1 g/prise, max 3 g/j\n- Anti-inflammatoire : 3-6 g/j (rarement utilisé à cette dose aujourd'hui)\n\n**Contre-indications**\n- Ulcère gastroduodénal évolutif\n- Hémophilie, troubles de la coagulation\n- Allergie aux salicylés ou aux AINS\n- Grossesse (3ème trimestre), enfant < 15 ans (risque syndrome de Reye)\n- Association avec anticoagulants (précaution)\n\n**Effets indésirables**\n- Ulcères gastroduodénaux, hémorragies digestives\n- Syndrome de Reye (enfants < 15 ans)\n- Acouphènes, vertiges (intoxication)\n- Syndrome hémorragique\n\n**Surveillance infirmière**\n- Ne jamais interrompre brusquement le traitement antiagrégant (risque thrombotique)\n- Informer l'anesthésiste (arrêt 5-7 j avant chirurgie réglée sauf si prescrit autrement)\n- Associer IPP si risque digestif\n- Éduquer sur les signes de saignement`, ['AINS', 'aspirine', 'antiagrégant plaquettaire', 'COX', 'cardiovasculaire', 'Reye', 'salicylé']) },

  { classIndex: 1, name: 'Piroxicam (Feldène®)', genericName: 'Piroxicam', description: 'AINS à longue demi-vie (38-50h), 1 prise par jour. Usage limité aux rhumatismes en raison du risque digestif et cutané supérieur aux autres AINS.',
    ...s(`**DCI :** Piroxicam\n**Noms commerciaux :** Feldène®, Brexin® (piroxicam β-cyclodextrine)\n\n**Mécanisme d'action**\nInhibiteur non sélectif des COX-1/COX-2. Demi-vie très longue (38-50 h) permettant 1 prise/j. Risque d'accumulation. Bonne efficacité anti-inflammatoire mais rapport bénéfice/risque moins favorable comparé aux AINS plus récents.\n\n**Indications principales**\n- Polyarthrite rhumatoïde\n- Arthrose symptomatique\n- Spondylarthrite ankylosante\n- Rhumatismes abarticulaires (tendinites, périarthrites)\n\n**Posologie adulte**\n- 20 mg/j en 1 prise per os avec le repas\n- Demi-vie longue : état d'équilibre atteint en 7-12 jours\n\n**Contre-indications**\n- Ulcère gastroduodénal, hémorragie digestive\n- Grossesse > 24 SA\n- Insuffisance hépatique, rénale ou cardiaque sévère\n- Sujet de plus de 65 ans (risque accru — préférer AINS à courte demi-vie)\n\n**Effets indésirables**\n- Risque digestif supérieur aux autres AINS (long-terme)\n- Photosensibilisation cutanée (érythèmes bullosités)\n- Réactions cutanées graves (Stevens-Johnson)\n\n**Surveillance infirmière**\n- Photosensibilisation : protéger du soleil pendant traitement\n- Durée minimale recommandée (risque cumulatif)\n- Signaler tout signe cutané (éruption, bulles)\n- Éviter chez le sujet âgé`, ['AINS', 'piroxicam', 'photosensibilisation', 'long-terme', 'rhumatologie', 'demi-vie longue']) },

  { classIndex: 1, name: 'Étoricoxib (Arcoxia®)', genericName: 'Étoricoxib', description: 'Coxib de deuxième génération, inhibiteur très sélectif de la COX-2. Longue demi-vie, 1 prise par jour. Efficace sur la douleur aiguë et la goutte.',
    ...s(`**DCI :** Étoricoxib\n**Noms commerciaux :** Arcoxia®\n\n**Mécanisme d'action**\nInhibiteur hautement sélectif de la COX-2 (105 fois plus sélectif que la COX-1). Longue demi-vie (22 h) → 1 prise/j. Même bénéfice digestif que le célécoxib mais risque cardiovasculaire similar.\n\n**Indications principales**\n- Arthrose\n- Polyarthrite rhumatoïde et rhumatisme psoriasique\n- Spondylarthrite ankylosante\n- Crise de goutte aiguë (60-120 mg/j, efficacité similaire à l'indométacine)\n- Douleurs post-opératoires en chirurgie dentaire\n\n**Posologie adulte**\n- Arthrose : 30-60 mg/j\n- PR/SPA : 60-90 mg/j\n- Goutte aiguë : 120 mg/j (max 8 jours)\n\n**Contre-indications**\n- Hypertension artérielle non contrôlée\n- Maladies cardiovasculaires (cardiopathie ischémique, insuffisance cardiaque, AVC)\n- Grossesse\n- Insuffisance hépatique modérée à sévère\n\n**Effets indésirables**\n- Rétention hydrosodée, HTA (surveiller PA)\n- Risque cardiovasculaire (thrombo-embolique)\n- Moins de risque digestif que les AINS classiques\n\n**Surveillance infirmière**\n- Mesurer la PA avant initiation et régulièrement\n- Interrompre si HTA non contrôlée\n- Ne pas utiliser chez patient avec facteurs de risque cardiovasculaire élevé`, ['AINS', 'étoricoxib', 'coxib', 'COX-2 sélectif', 'goutte', 'arthrose', 'cardiovasculaire']) },
];

/* ══════════════════════════════════════════════════════════════
   CLASSE 2 — Analgésiques — Antipyrétiques
══════════════════════════════════════════════════════════════ */

const analgesiques = [

  { classIndex: 2, name: 'Codéine (Codéine Bouchara®)', genericName: 'Codéine phosphate', description: 'Opioïde faible de palier II, prodrogue de la morphine. Antalgique et antitussif. Association fréquente avec le paracétamol (Di-Antalvic® retiré, Dafalgan Codéiné®).',
    ...s(`**DCI :** Codéine phosphate (hémihydrate)\n**Noms commerciaux :** Codéine Bouchara®, Dafalgan Codéiné® (association), Efferalgan Codéiné®\n\n**Mécanisme d'action**\nProdrug métabolisée en morphine (10 %) et codéine-6-glucuronide par le CYP2D6. Agoniste opioïde mu (μ). Effet antalgique de palier II (OMS) et antitussif central.\n\n**Indications principales**\n- Douleurs modérées à intenses ne répondant pas aux antalgiques de palier I seuls\n- Toux sèche non productive invalidante\n- En association avec le paracétamol (optimisation de l'analgésie)\n\n**Posologie adulte**\n- 20 à 60 mg/prise, toutes les 4-6 h, max 240 mg/j\n- Toujours associé au paracétamol dans les formes disponibles\n- Interdit chez l'enfant < 12 ans (CYP2D6 variable, risque de morphinisation supra-thérapeutique)\n\n**Contre-indications**\n- Enfant < 12 ans (AMM retirée)\n- Dépression respiratoire, asthme aigu grave\n- Insuffisance hépatique sévère\n- Allaitement (risque de surdosage du nourrisson)\n\n**Effets indésirables**\n- Constipation (quasi systématique)\n- Somnolence, vertiges\n- Nausées, vomissements\n- Dépendance physique et psychique (usage prolongé)\n- Dépression respiratoire (surdosage, métaboliseurs rapides du CYP2D6)\n\n**Surveillance infirmière**\n- Évaluation systématique de la douleur avant et après administration\n- Laxatif préventif systématique recommandé\n- Surveiller la fréquence respiratoire\n- Éduquer sur la dépendance et le mésusage`, ['analgésique', 'opioïde palier II', 'codéine', 'antitussif', 'prodrogue morphine', 'CYP2D6']) },

  { classIndex: 2, name: 'Tramadol (Topalgic®)', genericName: 'Tramadol chlorhydrate', description: 'Antalgique de palier II, opioïde faible avec propriétés monoaminergiques (inhibition recapture sérotonine et noradrénaline). Mécanisme d\'action double.',
    ...s(`**DCI :** Tramadol chlorhydrate\n**Noms commerciaux :** Topalgic®, Contramal®, Zamudol® (LP), Ixprim® (association paracétamol/tramadol)\n\n**Mécanisme d'action**\nDouble mécanisme : agoniste opioïde faible mu (μ) ET inhibiteur de la recapture de sérotonine et noradrénaline (similaire aux antidépresseurs IRSN). Synergie des deux effets pour l'analgésie.\n\n**Indications principales**\n- Douleurs modérées à sévères (palier II)\n- Douleurs neuropathiques (grâce à l'effet monoaminergique)\n- Post-opératoire\n- Douleurs cancéreuses\n\n**Posologie adulte**\n- Libération immédiate : 50-100 mg toutes les 4-6 h, max 400 mg/j\n- Libération prolongée (LP) : 100-200 mg x 2/j\n- Débuter à faible dose (réduire effets secondaires)\n\n**Contre-indications**\n- Épilepsie non contrôlée (abaisse le seuil épileptogène)\n- Association avec les IMAO (syndrome sérotoninergique)\n- Insuffisance hépatique sévère\n- Alcoolisme, intoxication aux opioïdes\n\n**Effets indésirables**\n- Nausées, vomissements (fréquents en début)\n- Somnolence, vertiges\n- Convulsions (doses élevées, interactions)\n- Syndrome sérotoninergique (associations)\n- Dépendance\n\n**Surveillance infirmière**\n- Surveiller apparition de crises épileptiques\n- Évaluer l'état de conscience (risque de sédation)\n- Prévenir les interactions : ISRS, IMAO, autres opioïdes\n- Laxatif préventif`, ['analgésique', 'opioïde palier II', 'tramadol', 'neuropathique', 'IRSN', 'sérotonine']) },

  { classIndex: 2, name: 'Morphine sulfate (Sevredol®)', genericName: 'Morphine sulfate', description: 'Opioïde puissant de palier III, analgésique de référence des douleurs sévères. Classé stupéfiant. Disponible en formes à libération immédiate et prolongée.',
    ...s(`**DCI :** Morphine sulfate\n**Noms commerciaux :** Sevredol® (LI), Skenan® (LP), Actiskenan® (LI), Morphine Cooper® (ampoules)\n\n**Mécanisme d'action**\nAgoniste opioïde des récepteurs mu (μ), kappa (κ) et delta (δ). Inhibition centrale de la transmission douloureuse. Soulagement des douleurs intenses et chroniques. Analgésie, sédation, euphorie, dépression respiratoire dépendants de la dose.\n\n**Indications principales**\n- Douleurs sévères ne répondant pas aux paliers I et II\n- Douleurs cancéreuses chroniques (traitement de fond)\n- Douleurs post-opératoires sévères\n- Douleurs aiguës intenses (traumatisme grave, infarctus du myocarde)\n- Dyspnée terminale en soins palliatifs\n\n**Posologie adulte**\n- LI : 5-15 mg toutes les 4 h per os (titration individuelle)\n- LP : toutes les 12-24 h (dose calculée sur base LI)\n- IV : 0,05-0,1 mg/kg en titration ou PCA\n- Pas de dose maximale fixe (titration selon la douleur)\n\n**Contre-indications**\n- Dépression respiratoire sévère (absolue)\n- Traumatisme crânien grave (masque l'aggravation neurologique)\n- Insuffisance hépatique sévère\n- Iléus paralytique\n\n**Effets indésirables**\n- Dépression respiratoire (surdosage)\n- Constipation (systématique → laxatifs prophylactiques obligatoires)\n- Nausées, vomissements\n- Somnolence, confusion (surtout chez le sujet âgé)\n- Rétention urinaire\n- Dépendance physique\n\n**Antidote :** Naloxone (Narcan®) — titration par petits bolus\n\n**Surveillance infirmière**\n- Fréquence respiratoire > 12/min avant injection\n- Score de sédation (RASS, échelle de Rudkin)\n- EVA/ENS régulières pour adaptation posologique\n- Laxatif obligatoire dès J1\n- Traçabilité stricte (stupéfiant)`, ['opioïde', 'morphine', 'palier III', 'stupéfiant', 'antalgique', 'soins palliatifs', 'naloxone']) },

  { classIndex: 2, name: 'Oxycodone (Oxycontin®)', genericName: 'Oxycodone chlorhydrate', description: 'Opioïde puissant de palier III, similaire à la morphine avec une meilleure biodisponibilité orale (environ 60-90%). Alternative à la morphine en cas de mauvaise tolérance.',
    ...s(`**DCI :** Oxycodone chlorhydrate\n**Noms commerciaux :** Oxycontin® (LP), Oxynorm® (LI), Oxynormoro® (LI lyophilisat oral)\n\n**Mécanisme d'action**\nAgoniste opioïde mu (μ) et kappa (κ). Meilleure biodisponibilité orale que la morphine (~80% vs ~30%). Puissance antalgique comparable à la morphine (ratio oral 1:1,5 avec morphine).\n\n**Indications principales**\n- Douleurs sévères chroniques cancéreuses\n- Douleurs non cancéreuses sévères résistantes aux paliers inférieurs\n- Alternative à la morphine en cas de mauvaise tolérance (constipation sévère, hallucinations)\n\n**Posologie adulte**\n- LI (Oxynorm®) : 5-10 mg toutes les 4-6 h\n- LP (Oxycontin®) : toutes les 12 h (dose basale + interdoses)\n- Rotation opioïde depuis morphine : ratio morphine/oxycodone orale = 1,5:1\n\n**Contre-indications**\n- Mêmes que la morphine\n- Iléus paralytique\n\n**Effets indésirables**\n- Constipation (fréquente, laxatifs préventifs)\n- Nausées, somnolence\n- Dépression respiratoire (surdosage)\n- Fort potentiel de mésusage (risque d'addiction)\n\n**Surveillance infirmière**\n- Même surveillance que la morphine\n- Attention au mésusage : comprimés LP ne doivent pas être écrasés\n- Traçabilité stricte (stupéfiant)\n- Évaluation douleur régulière`, ['opioïde', 'oxycodone', 'palier III', 'stupéfiant', 'douleur chronique', 'rotation opioïde']) },

  { classIndex: 2, name: 'Fentanyl transdermique (Durogesic®)', genericName: 'Fentanyl', description: 'Opioïde puissant administré par voie transdermique (patch 72h) ou transmuqueuse. Réservé aux douleurs chroniques sévères stabilisées. 100 fois plus puissant que la morphine.',
    ...s(`**DCI :** Fentanyl (citrate)\n**Noms commerciaux :** Durogesic® (patch), Actiq® (citrate oral transmuqueux), Abstral® (sublingual), Breakyl® (buccal)\n\n**Mécanisme d'action**\nAgoniste opioïde puissant et sélectif des récepteurs mu (μ). Hautement liposoluble → excellent passage transdermique. 100 à 150 fois plus puissant que la morphine. Fentanyl transmuqueux : action en 5-15 min pour les accès douloureux paroxystiques.\n\n**Indications principales**\n- Patch : douleurs chroniques sévères stabilisées nécessitant un traitement opioïde continu (notamment si voie orale impossible)\n- Formes transmuqueuses : accès douloureux paroxystiques (ADP) sur fond de douleur chronique opioïde\n\n**Posologie adulte**\n- Patch : 12 à 100 μg/h toutes les 72 h (titration selon équivalence morphine)\n- Ne jamais couper le patch\n- Formes transmuqueuses : titration individuelle stricte\n\n**Contre-indications**\n- Douleurs aigues et post-opératoires (patch absolument contre-indiqué)\n- Patient non équilibré par opioïdes (initiation sous morphine orale obligatoire)\n- Fièvre élevée (augmente l'absorption transcutanée)\n\n**Effets indésirables**\n- Dépression respiratoire (risque majeur en cas de fièvre, chaleur locale)\n- Constipation\n- Somnolence, confusion\n- Réactions cutanées au site d'application\n\n**Surveillance infirmière**\n- Rotation des sites : bras, poitrine, dos (peau propre, sèche, sans poils)\n- Ne jamais exposer le patch à la chaleur (bain chaud, bouillotte, soleil)\n- Surveiller fréquence respiratoire\n- Élimination sécurisée des patchs usagés (contiennent encore du fentanyl)\n- Traçabilité stricte (stupéfiant)`, ['opioïde', 'fentanyl', 'transdermique', 'patch', 'stupéfiant', 'accès douloureux', 'soins palliatifs']) },

  { classIndex: 2, name: 'Buprénorphine (Temgésic®)', genericName: 'Buprénorphine', description: 'Agoniste-antagoniste partiel des récepteurs opioïdes. Antalgique et traitement de substitution aux opioïdes (Subutex®). Effet plafond pour la dépression respiratoire.',
    ...s(`**DCI :** Buprénorphine chlorhydrate\n**Noms commerciaux :** Temgésic® (antalgique), Subutex® (substitution), Suboxone® (buprénorphine+naloxone)\n\n**Mécanisme d'action**\nAgoniste partiel haute affinité des récepteurs mu (μ) et antagoniste kappa (κ). Effet antalgique puissant. Dissociation lente des récepteurs → longue durée d'action. Effet plafond sur la dépression respiratoire (sécurité relative en cas de surdosage).\n\n**Indications principales**\n- Temgésic® : douleurs sévères (post-opératoires, cancéreuses), par voie sublinguale\n- Subutex® / Suboxone® : traitement de substitution aux opioïdes (héroïne, morphine)\n- Traitement de la dépendance aux opiacés dans le cadre de la réduction des risques\n\n**Posologie adulte**\n- Antalgique : 0,2 à 0,4 mg sublingual x 3/j\n- Substitution : 8 à 24 mg/j sublingual\n\n**Contre-indications**\n- Insuffisance respiratoire sévère\n- Association avec les benzodiazépines (risque de dépression respiratoire synergique)\n- Association IMAO\n\n**Effets indésirables**\n- Nausées, vomissements, céphalées\n- Somnolence\n- Syndrome de sevrage si arrêt brutal (après usage prolongé)\n- Hépatite cytolytique (Subutex® IV — mésusage)\n\n**Surveillance infirmière**\n- Comprimé sublingual : ne pas avaler, laisser fondre sous la langue\n- Antagoniste partiel → peut déclencher un syndrome de sevrage chez opioïdodépendants non préparés\n- Surveillance FR si association avec benzodiazépines`, ['opioïde', 'buprénorphine', 'agoniste partiel', 'substitution', 'Subutex', 'douleur chronique']) },

  { classIndex: 2, name: 'Nalbuphine (Nubain®)', genericName: 'Nalbuphine chlorhydrate', description: 'Opioïde agoniste-antagoniste (agoniste kappa, antagoniste partiel mu). Antalgique de palier II-III injectable, non stupéfiant. Fréquemment utilisé en SAMU et urgences.',
    ...s(`**DCI :** Nalbuphine chlorhydrate\n**Noms commerciaux :** Nubain®\n\n**Mécanisme d'action**\nAgoniste des récepteurs kappa (κ) opioïdes ET antagoniste partiel des récepteurs mu (μ). Effet antalgique de palier III par la voie kappa, avec un effet plafond sur la dépression respiratoire. Non classé stupéfiant en France → avantage logistique en urgence.\n\n**Indications principales**\n- Douleurs aiguës intenses aux urgences, SAMU, SMUR\n- Douleurs post-opératoires (analgésie IVD en salle de réveil)\n- Douleurs obstétricales\n- Analgésie procédurale (réductions de fractures, soins douloureux)\n\n**Posologie adulte**\n- IV lente : 0,2 mg/kg (environ 10-20 mg) en 5 min\n- SC/IM : 10-20 mg toutes les 3-6 h\n- Peut être répétée selon EVA\n\n**Contre-indications**\n- Dépression respiratoire\n- ATCD addiction aux opioïdes (peut précipiter un syndrome de sevrage)\n- Association avec agonistes purs opioïdes (antagonisme)\n\n**Effets indésirables**\n- Somnolence, nausées\n- Dysphorie (effets kappa)\n- Dépression respiratoire (moins marquée qu'avec la morphine)\n- Sudation\n\n**Surveillance infirmière**\n- FR, SpO2, PA après injection\n- Évaluation douleur avant et 15-30 min après\n- Non stupéfiant : pas de prescription sur ordonnance sécurisée ni de traçabilité spécifique\n- Antidote : naloxone (moins efficace car antagonisme partiel mu)`, ['opioïde', 'nalbuphine', 'urgences', 'SAMU', 'non stupéfiant', 'agoniste-antagoniste', 'antalgique IV']) },

  { classIndex: 2, name: 'Néfopam (Acupan®)', genericName: 'Néfopam chlorhydrate', description: 'Antalgique central non opioïde, non AINS. Mécanisme unique, sans dépression respiratoire. Utilisé en analgésie multimodale post-opératoire.',
    ...s(`**DCI :** Néfopam chlorhydrate\n**Noms commerciaux :** Acupan®\n\n**Mécanisme d'action**\nInhibiteur de la recapture centrale de la sérotonine, noradrénaline et dopamine. Inhibe également les canaux sodiques. Mécanisme distinct des opioïdes et des AINS. Pas de dépression respiratoire, pas de dépendance. Pas d'effet antipyrétique.\n\n**Indications principales**\n- Douleurs post-opératoires modérées à sévères (analgésie multimodale)\n- Douleurs chroniques non cancéreuses\n- Alternative aux opioïdes pour limiter la consommation morphinique\n\n**Posologie adulte**\n- IV lente (au moins 15 min) : 20 mg toutes les 4-6 h (max 120 mg/j)\n- IM : 20 mg toutes les 6 h\n- IVSE possible : 80-120 mg/24 h\n\n**Contre-indications**\n- Épilepsie ou risque épileptogène\n- Glaucome à angle fermé (effet atropinique)\n- Adénome de la prostate avec rétention urinaire\n- Grossesse (pas d'évaluation suffisante)\n\n**Effets indésirables**\n- Tachycardie, sueurs (effet atropinique — fréquent)\n- Nausées, vomissements\n- Somnolence, vertiges\n- Rétention urinaire (effet anticholinergique)\n- Convulsions (surdosage)\n\n**Surveillance infirmière**\n- Injection IV LENTE (risque de sueurs, tachycardie si trop rapide)\n- Surveiller FC et PA\n- Ne pas injecter directement (diluer dans 100 mL)\n- Surveiller diurèse (risque de rétention urinaire)\n- Prévenir le patient des sueurs et palpitations`, ['analgésique', 'néfopam', 'post-opératoire', 'non opioïde', 'non AINS', 'multimodale', 'atropinique']) },

  { classIndex: 2, name: 'Naloxone (Narcan®)', genericName: 'Naloxone chlorhydrate', description: 'Antagoniste pur des récepteurs opioïdes. Antidote des surdosages opioïdes. Renverse la dépression respiratoire en quelques minutes. Administrable par toute personne formée.',
    ...s(`**DCI :** Naloxone chlorhydrate\n**Noms commerciaux :** Narcan® (IV/IM), Nalscue® (nasal), Prenoxad® (nasal)\n\n**Mécanisme d'action**\nAntagoniste compétitif pur et sélectif des récepteurs opioïdes mu (μ), kappa (κ) et delta (δ). Déplace les opioïdes de leurs récepteurs. Renverse tous les effets opioïdes en 2-5 min IV. Demi-vie courte (30-80 min) : risque de re-sédation si l'opioïde a une demi-vie longue (fentanyl, morphine LP).\n\n**Indications principales**\n- Surdosage aigu aux opioïdes (dépression respiratoire, coma)\n- Renversement de l'analgésie opioïde en post-opératoire (si dépression respiratoire)\n- Prévention des rechutes chez les patients opioïdodépendants (naltrexone)\n- Sous forme nasale : kit de secours pour patients opioïdodépendants et entourage\n\n**Posologie adulte**\n- Surdosage : 0,4 mg IV toutes les 2-3 min jusqu'à réponse (FR > 12/min)\n- En titration pour éviter de déclencher un syndrome de sevrage brutal\n- IVSE si opioïde à longue demi-vie : 0,25-1 μg/kg/h\n\n**Contre-indications**\n- Allergie à la naloxone\n- Précaution : cardiovasculaires graves (risque d'arythmies si réveil brutal après opioïdes)\n\n**Effets indésirables**\n- Syndrome de sevrage aigu si patient dépendant : douleurs intenses, agitation, sueurs, vomissements\n- Tachycardie, HTA (réveil douloureux)\n- Dépression respiratoire récurrente (re-sédation) après diminution de l'effet naloxone\n\n**Surveillance infirmière**\n- URGENCE : avoir la naloxone prête dans toute unité utilisant des opioïdes\n- Surveiller FR et SpO2 en continu\n- Surveiller pendant au moins 2 h après administration (re-sédation)\n- Former les patients opioïdodépendants et leurs proches à l'utilisation nasale (Nalscue®)`, ['antidote', 'naloxone', 'antagoniste opioïde', 'surdosage', 'dépression respiratoire', 'urgence', 'Narcan']) },
];

module.exports = { antibiotiques, ains, analgesiques };
