/**
 * seedMed_p2.js — 30 médicaments
 * Classe 3 : IEC (drogues 2-10)
 * Classe 4 : Anticoagulants (drogues 2-10)
 * Classe 5 : Corticoïdes (drogues 2-10)
 */

function s(general, tags) {
  return {
    sections: [
      { title: 'Général', content: general, order: 0 },
      { title: 'Médias',  content: 'Schémas et ressources pédagogiques disponibles dans les supports de cours IFSI et sur le site de l\'ANSM.', order: 1 },
      { title: 'Source',  content: '**Références**\n1. ANSM — Monographie du médicament. [ansm.sante.fr]\n2. Vidal — Fiche médicament. [vidal.fr]\n3. HAS — Recommandations de bon usage. [has-sante.fr]\n4. Société savante de référence — Recommandations cliniques.', order: 2 },
    ],
    sources: [
      { title: 'ANSM — Monographie', authors: 'ANSM', year: '2023', url: 'https://ansm.sante.fr' },
      { title: 'Vidal',              authors: 'Vidal', year: '2023', url: 'https://vidal.fr' },
    ],
    tags,
  };
}

/* ══════════════════════════════════════════════════════════════
   CLASSE 3 — Inhibiteurs de l'enzyme de conversion (IEC)
══════════════════════════════════════════════════════════════ */

const iec = [

  { classIndex: 3, name: 'Énalapril (Renitec®)', genericName: 'Énalapril maléate', description: 'IEC prodrogue transformée en énalaprilate (forme active). L\'un des premiers IEC disponibles, référence de la classe.',
    ...s(`**DCI :** Énalapril maléate\n**Noms commerciaux :** Renitec®, Énalapril Mylan®\n\n**Mécanisme d'action**\nProdrogue transformée en énalaprilate par hydrolyse hépatique. Inhibe l'enzyme de conversion (ECA), bloquant la conversion angiotensine I → angiotensine II. Vasodilatation artérielle et veineuse. Réduction de l'aldostérone.\n\n**Indications principales**\n- Hypertension artérielle essentielle\n- Insuffisance cardiaque systolique symptomatique\n- Dysfonction ventriculaire gauche asymptomatique post-IDM\n- Néphropathie diabétique\n\n**Posologie adulte**\n- HTA : 5 mg/j initialement, augmentation jusqu'à 20-40 mg/j en 1-2 prises\n- IC : 2,5 mg/j initialement, objectif 10-20 mg x 2/j\n\n**Contre-indications**\n- Allergie aux IEC, angio-œdème sous IEC\n- Grossesse (2ème et 3ème trimestre)\n- Sténose bilatérale des artères rénales\n\n**Effets indésirables**\n- Toux sèche (10-20%)\n- Hyperkaliémie\n- Hypotension de la première dose\n- Insuffisance rénale fonctionnelle\n- Angio-œdème (rare)\n\n**Surveillance infirmière**\n- PA avant prise (première dose surtout)\n- Kaliémie, créatinine régulièrement\n- Éduquer sur la toux et l'angio-œdème\n- Lever lentement (hypotension orthostatique)`, ['IEC', 'énalapril', 'antihypertenseur', 'SRAA', 'IC', 'insuffisance cardiaque']) },

  { classIndex: 3, name: 'Lisinopril (Zestril®)', genericName: 'Lisinopril', description: 'IEC non prodrogue (actif directement), éliminé uniquement par voie rénale. 1 prise par jour.',
    ...s(`**DCI :** Lisinopril dihydrate\n**Noms commerciaux :** Zestril®, Prinivil®, Lisinopril Mylan®\n\n**Mécanisme d'action**\nSeul IEC non prodrogue (actif directement, sans transformation hépatique). Inhibition de l'ECA → vasodilatation, baisse de l'aldostérone. Éliminé exclusivement par voie rénale → adapter la dose en IR.\n\n**Indications principales**\n- HTA essentielle\n- Insuffisance cardiaque congestive\n- IDM récent avec insuffisance ventriculaire gauche\n- Néphropathie diabétique type 1\n\n**Posologie adulte**\n- HTA : 10 mg/j initialement, objectif 20-40 mg/j en 1 prise\n- IC : 2,5-5 mg/j initialement\n- Adapter si clairance créatinine < 30 mL/min\n\n**Contre-indications**\n- Identiques aux autres IEC\n- Insuffisance rénale sévère (accumulation par absence de métabolisme hépatique)\n\n**Effets indésirables**\n- Toux sèche, hyperkaliémie, hypotension\n- Angio-œdème\n- Dégradation de la fonction rénale\n\n**Surveillance infirmière**\n- Surveillance rénale renforcée (élimination 100% rénale)\n- 1 prise/j : favorise l'observance\n- Interrompre si chirurgie lourde ou déshydratation`, ['IEC', 'lisinopril', 'antihypertenseur', 'non prodrogue', 'HTA', 'insuffisance cardiaque']) },

  { classIndex: 3, name: 'Périndopril (Coversyl®)', genericName: 'Périndopril', description: 'IEC prodrogue (périndoprilate forme active). Longue durée d\'action, 1 prise/j. Indiqué dans la prévention secondaire cardiovasculaire.',
    ...s(`**DCI :** Périndopril (erbumine ou arginine)\n**Noms commerciaux :** Coversyl®, Périndopril Mylan®\n\n**Mécanisme d'action**\nProdrogue hydrolysée en périndoprilate (actif). Inhibiteur puissant de l'ECA, longue demi-vie → 1 prise/j. Propriétés vasculoprotectrices démontrées dans les études cliniques (EUROPA, ADVANCE).\n\n**Indications principales**\n- HTA essentielle\n- Insuffisance cardiaque\n- Prévention secondaire des événements cardiovasculaires chez coronarien stable\n- Réduction du risque cardiovasculaire chez diabétique type 2 (avec indapamide)\n\n**Posologie adulte**\n- HTA : 4 mg/j, augmentable à 8 mg/j en 1 prise le matin\n- Prévention CV : 8 mg/j\n\n**Contre-indications**\n- Identiques aux autres IEC\n\n**Effets indésirables**\n- Toux sèche, hyperkaliémie, hypotension\n- Dégradation rénale (surveillance créatinine)\n\n**Surveillance infirmière**\n- Prise le matin à jeun ou avant le repas\n- PA, kaliémie, créatinine régulièrement\n- Association fréquente avec indapamide (Bipreterax®) → surveiller la natrémie`, ['IEC', 'périndopril', 'Coversyl', 'antihypertenseur', 'prévention cardiovasculaire', 'coronarien']) },

  { classIndex: 3, name: 'Captopril (Lopril®)', genericName: 'Captopril', description: 'Premier IEC commercialisé, à courte durée d\'action (2-3 prises/j). Contient un groupe thiol → effets spécifiques (protéinurie, goût métallique).',
    ...s(`**DCI :** Captopril\n**Noms commerciaux :** Lopril®, Captopril Mylan®\n\n**Mécanisme d'action**\nPremier IEC découvert (1975). Actif directement (non prodrogue). Contient un groupe sulfhydryle (thiol) qui lui confère une légère différence : protéinurie plus fréquente, goût métallique. Courte demi-vie → 2-3 prises/j.\n\n**Indications principales**\n- HTA essentielle\n- Insuffisance cardiaque\n- Post-IDM avec dysfonction VG\n- Néphropathie diabétique\n- Crise hypertensive (usage sublingual dans certains contextes)\n\n**Posologie adulte**\n- HTA : 25-50 mg x 2-3/j à jeun\n- IC : 6,25-50 mg x 3/j\n- Crise HTA : 25 mg per os ou sublingual (action en 15-30 min)\n\n**Contre-indications**\n- Identiques aux autres IEC\n\n**Effets indésirables**\n- Toux sèche (fréquente)\n- Goût métallique (groupe thiol)\n- Protéinurie (groupe thiol — surveiller)\n- Hypotension\n- Rash cutané (plus fréquent que les autres IEC)\n\n**Surveillance infirmière**\n- Prendre à jeun (absorption réduite de 30% par nourriture)\n- Surveiller protéinurie sur bandelette\n- 3 prises/j : informer sur l'importance de l'observance`, ['IEC', 'captopril', 'premier IEC', 'antihypertenseur', 'thiol', 'crise hypertensive']) },

  { classIndex: 3, name: 'Fosinopril (Fozitec®)', genericName: 'Fosinopril sodique', description: 'Seul IEC à double élimination hépatique ET rénale. Intéressant dans l\'insuffisance rénale sans ajustement de dose si l\'élimination hépatique compense.',
    ...s(`**DCI :** Fosinopril sodique\n**Noms commerciaux :** Fozitec®\n\n**Mécanisme d'action**\nProdrogue hydrolysée en fosinoprilate (actif). Seul IEC à double voie d'élimination (hépatique 50% + rénale 50%). En cas d'insuffisance rénale, l'élimination hépatique augmente compensatoirement → accumulation moins prononcée.\n\n**Indications principales**\n- HTA essentielle\n- Insuffisance cardiaque\n- Indication particulière : HTA chez l'insuffisant rénal modéré\n\n**Posologie adulte**\n- HTA : 10 mg/j initialement, augmentable à 40 mg/j en 1 prise\n- Moins d'adaptation de dose nécessaire en IR modérée\n\n**Contre-indications**\n- Identiques aux autres IEC\n\n**Effets indésirables**\n- Toux sèche, hyperkaliémie, hypotension\n- Insuffisance rénale fonctionnelle\n\n**Surveillance infirmière**\n- Surveillance rénale et ionique\n- Avantage pharmacocinétique en cas d'IR modérée mais vigilance maintenue\n- PA avant chaque prise`, ['IEC', 'fosinopril', 'double élimination', 'insuffisance rénale', 'antihypertenseur']) },

  { classIndex: 3, name: 'Quinapril (Acuitel®)', genericName: 'Quinapril chlorhydrate', description: 'IEC prodrogue transformée en quinaprilate. Bonne pénétration tissulaire. Indiqué dans l\'HTA et l\'insuffisance cardiaque.',
    ...s(`**DCI :** Quinapril chlorhydrate\n**Noms commerciaux :** Acuitel®, Korec®\n\n**Mécanisme d'action**\nProdrogue convertie en quinaprilate (actif) par hydrolyse hépatique. Forte affinité tissulaire pour l'ECA (rénale, cardiaque) → bonne inhibition tissulaire du SRAA.\n\n**Indications principales**\n- HTA essentielle\n- Insuffisance cardiaque (en association)\n\n**Posologie adulte**\n- HTA : 10 mg/j initialement, objectif 20-40 mg/j en 1-2 prises\n- IC : 5 mg x 2/j initialement\n\n**Contre-indications**\n- Identiques aux autres IEC\n\n**Effets indésirables**\n- Toux sèche, hyperkaliémie, hypotension\n- Dégradation rénale\n\n**Surveillance infirmière**\n- PA avant prise\n- Bilan rénal et ionique régulier\n- Éduquer sur les signes d'alerte (toux, angio-œdème)`, ['IEC', 'quinapril', 'antihypertenseur', 'SRAA', 'HTA', 'IC']) },

  { classIndex: 3, name: 'Trandolapril (Odrik®)', genericName: 'Trandolapril', description: 'IEC prodrogue à longue durée d\'action (24-36h). 1 prise/j. Indiqué dans l\'HTA et en post-IDM pour réduire la mortalité cardiovasculaire.',
    ...s(`**DCI :** Trandolapril\n**Noms commerciaux :** Odrik®, Gopten®\n\n**Mécanisme d'action**\nProdrogue hydrolysée en trandolaprilate (actif). Longue demi-vie d'élimination du métabolite actif (15-23 h) → 1 prise/j possible. Données cliniques sur la réduction de mortalité post-IDM (étude TRACE).\n\n**Indications principales**\n- HTA essentielle\n- Post-infarctus avec dysfonction ventriculaire gauche (réduction de mortalité démontrée)\n- Insuffisance cardiaque\n\n**Posologie adulte**\n- HTA : 1-2 mg/j en 1 prise\n- Post-IDM : 1 mg/j initialement (3e-7e jour post-IDM), objectif 4 mg/j\n\n**Contre-indications**\n- Identiques aux autres IEC\n\n**Effets indésirables**\n- Toux sèche, hyperkaliémie, hypotension\n- Dégradation de la fonction rénale\n\n**Surveillance infirmière**\n- Débuter en milieu hospitalier en post-IDM\n- Surveillance PA et FC (risque d'hypotension)\n- Créatinine et kaliémie J7 et J30`, ['IEC', 'trandolapril', 'post-IDM', 'antihypertenseur', 'cardioprotection', 'mortalité']) },

  { classIndex: 3, name: 'Zofénopril (Zofenil®)', genericName: 'Zofénopril calcique', description: 'IEC lipophile à groupe thiol, cardioprotecteur. Indiqué spécifiquement dans l\'IDM aigu avec insuffisance ventriculaire gauche débutante.',
    ...s(`**DCI :** Zofénopril calcique\n**Noms commerciaux :** Zofenil®\n\n**Mécanisme d'action**\nProdrogue avec groupe thiol (comme captopril). Haute lipophilie → bonne pénétration tissulaire cardiaque. Propriétés antioxydantes (groupe thiol). Étudiée spécifiquement dans le SCA (infarctus).\n\n**Indications principales**\n- IDM aigu sans insuffisance cardiaque sévère ni choc cardiogénique (dans les 24 premières heures)\n- HTA essentielle légère à modérée\n\n**Posologie adulte**\n- IDM aigu : 7,5 mg x 2/j pendant 24 h, puis augmentation progressive jusqu'à 30 mg x 2/j\n- HTA : 30-60 mg/j en 1-2 prises\n\n**Contre-indications**\n- Identiques aux autres IEC\n- Choc cardiogénique (contre-indiqué dans l'IDM avec choc)\n\n**Effets indésirables**\n- Toux sèche, hyperkaliémie, hypotension\n\n**Surveillance infirmière**\n- Surveillance hémodynamique renforcée en phase aiguë d'IDM\n- PA et FC monitorisées\n- Surveillance rénale et ionique`, ['IEC', 'zofénopril', 'IDM', 'thiol', 'cardioprotection', 'antihypertenseur']) },

  { classIndex: 3, name: 'Cilazapril (Justor®)', genericName: 'Cilazapril monohydrate', description: 'IEC prodrogue de longue durée d\'action. 1 prise quotidienne. Indiqué dans l\'HTA et l\'insuffisance cardiaque.',
    ...s(`**DCI :** Cilazapril monohydrate\n**Noms commerciaux :** Justor®, Inhibace®\n\n**Mécanisme d'action**\nProdrogue hydrolysée en cilazaprilate (actif). Demi-vie longue du métabolite actif → 1 prise/j. Propriétés similaires aux autres IEC de la classe.\n\n**Indications principales**\n- HTA essentielle légère à sévère\n- Insuffisance cardiaque congestive (en complément de diurétiques et glycosides)\n\n**Posologie adulte**\n- HTA : 2,5 mg/j initialement, objectif 2,5-5 mg/j en 1 prise\n- IC : 0,5 mg/j initialement, augmentation progressive\n\n**Contre-indications**\n- Identiques aux autres IEC\n\n**Effets indésirables**\n- Toux sèche, hyperkaliémie, hypotension\n- Dégradation rénale\n\n**Surveillance infirmière**\n- PA, créatinine, kaliémie\n- Risque d'hypotension lors de la première prise\n- Éduquer à la prise quotidienne régulière`, ['IEC', 'cilazapril', 'antihypertenseur', 'SRAA', 'HTA', 'IC']) },
];

/* ══════════════════════════════════════════════════════════════
   CLASSE 4 — Anticoagulants
══════════════════════════════════════════════════════════════ */

const anticoagulants = [

  { classIndex: 4, name: 'Énoxaparine (Lovenox®)', genericName: 'Énoxaparine sodique', description: 'Héparine de bas poids moléculaire (HBPM), la plus utilisée en France. Injection SC 1 à 2 fois par jour. Ne nécessite pas de surveillance de l\'anticoagulation en routine.',
    ...s(`**DCI :** Énoxaparine sodique\n**Noms commerciaux :** Lovenox®, Énoxaparine Mylan®\n\n**Mécanisme d'action**\nHBPM : fragments d'héparine de faible poids moléculaire. Inhibe principalement le facteur Xa (ratio anti-Xa/anti-IIa = 3,5:1), moins la thrombine que l'HNF. Biodisponibilité SC quasi complète (~90%). Pas de monitorage de l'anticoagulation en routine (sauf situations particulières).\n\n**Indications principales**\n- Prévention MTEV en chirurgie orthopédique, abdominale et médecine\n- Traitement curatif TVP et EP (en relais des AOD ou seule)\n- Traitement du SCA (NSTEMI, STEMI)\n- Anticoagulation en angioplastie coronaire\n- Relais péri-opératoire des AVK\n\n**Posologie adulte**\n- Préventive : 4 000 UI SC x 1/j (haut risque) ou 2 000 UI x 1/j (risque modéré)\n- Curative TVP/EP : 100 UI/kg SC x 2/j ou 150 UI/kg x 1/j\n- SCA NSTEMI : 100 mg/kg SC x 2/j + aspirine\n\n**Contre-indications**\n- ATCD de TIH (absolue)\n- Hémorragie active\n- Insuffisance rénale sévère (DFG < 15 mL/min) — accumulation\n\n**Effets indésirables**\n- Hémorragies (site d'injection, surdosage)\n- TIH type II (plus rare qu'avec HNF : 0,2-0,3 %)\n- Hématome au site d'injection\n- Ostéoporose (traitement prolongé)\n\n**Surveillance infirmière**\n- NFS-plaquettes J1, J5, J7, J14 (dépistage TIH)\n- Anti-Xa si IR, extrêmes de poids, grossesse\n- Technique SC : abdomen, pincer peau, ne pas frotter après injection\n- Alterner les sites d'injection`, ['HBPM', 'énoxaparine', 'anticoagulant', 'Lovenox', 'anti-Xa', 'MTEV', 'SC']) },

  { classIndex: 4, name: 'Warfarine (Coumadine®)', genericName: 'Warfarine sodique', description: 'AVK (Anti-Vitamine K) à longue demi-vie (36-42h). Anticoagulant oral de référence historique, nécessitant une surveillance régulière par l\'INR.',
    ...s(`**DCI :** Warfarine sodique\n**Noms commerciaux :** Coumadine®\n\n**Mécanisme d'action**\nInhibiteur de la vitamine K époxyde réductase → blocage de la carboxylation hépatique des facteurs II, VII, IX, X et des protéines C et S. Délai d'action de 48-72 h (épuisement des facteurs déjà synthétisés). Demi-vie longue (36-42 h).\n\n**Indications principales**\n- Fibrillation auriculaire (ACFA) avec risque embolique (score CHA₂DS₂-VASc)\n- Valvulopathies mitrales, prothèses valvulaires mécaniques (cibles INR élevées)\n- TVP et EP (traitement et prévention secondaire)\n- Syndrome des antiphospholipides\n\n**Posologie adulte**\n- Dose de départ : 5 mg/j (2,5 mg si sujet âgé, petits gabarits)\n- Adapation sur INR (résultat J3-J5) selon nomogramme\n- INR cible : 2-3 (FA, TVP) ou 2,5-3,5 (prothèse mécanique mitrale)\n\n**Contre-indications**\n- Hémorragie active ou risque hémorragique élevé\n- Grossesse (embryopathie aux coumarines)\n- HTA non contrôlée\n- Difficultés de surveillance de l'INR\n\n**Effets indésirables**\n- Hémorragies (surdosage INR) — majeur\n- Nécrose cutanée (rare — déficit en protéine C)\n- Interactions médicamenteuses ++ (nombreuses)\n\n**Antidote :** Vitamine K (Vitamine K1® per os ou IV) ± Octaplas® (PFC) si urgence hémorragique\n\n**Surveillance infirmière**\n- INR : contrôle avant initiation, J3-J5, puis toutes les 4-8 semaines à l'équilibre\n- Carnet de surveillance AVK obligatoire\n- Informer sur les interactions alimentaires (chou, épinards, brocolis — vitamine K)\n- Éduquer : signaler tout saignement inhabituel, éviter les sports à risque\n- Carte de porteur d'AVK`, ['AVK', 'warfarine', 'anticoagulant oral', 'INR', 'fibrillation auriculaire', 'vitamine K']) },

  { classIndex: 4, name: 'Dabigatran (Pradaxa®)', genericName: 'Dabigatran étexilate', description: 'Anticoagulant oral direct (AOD), inhibiteur direct de la thrombine (facteur IIa). 1ère classe d\'AOD. Pas de surveillance de l\'anticoagulation en routine.',
    ...s(`**DCI :** Dabigatran étexilate mésilate\n**Noms commerciaux :** Pradaxa®\n\n**Mécanisme d'action**\nProdrogue transformée en dabigatran (actif). Inhibiteur direct compétitif et réversible de la thrombine (facteur IIa) libre et liée au caillot. Pas d'interaction avec la vitamine K. Élimination rénale à 80% → attention si IR.\n\n**Indications principales**\n- Prévention de l'AVC et embolie systémique dans la FA non valvulaire\n- Traitement et prévention secondaire de la TVP et EP\n- Prophylaxie MTEV après PTH et PTG\n\n**Posologie adulte**\n- FA : 150 mg x 2/j (110 mg x 2/j si > 80 ans, risque hémorragique élevé)\n- TVP/EP : 150 mg x 2/j (après 5-10j de traitement parentéral)\n- Prophylaxie orthopédique : 220 mg/j en 1 prise\n\n**Contre-indications**\n- DFG < 30 mL/min (FA) ou < 50 mL/min (traitement TVP/EP)\n- Hémorragie active\n- Prothèse valvulaire mécanique\n\n**Effets indésirables**\n- Hémorragies (all sites)\n- Dyspepsie, douleurs épigastriques (20 % des patients → souvent résolutif)\n- Pas de TIH\n\n**Antidote :** Idarucizumab (Praxbind®) — antagoniste spécifique\n\n**Surveillance infirmière**\n- Pas de surveillance INR\n- Contrôle créatinine avant initiation et annuellement\n- Avaler les gélules entières (ne pas ouvrir)\n- Éduquer sur les signes hémorragiques\n- Si chirurgie : arrêt 24-48 h avant selon risque`, ['AOD', 'dabigatran', 'anti-IIa', 'anticoagulant oral', 'FA', 'idarucizumab', 'MTEV']) },

  { classIndex: 4, name: 'Rivaroxaban (Xarelto®)', genericName: 'Rivaroxaban', description: 'AOD inhibiteur direct du facteur Xa. 1 ou 2 prises/j selon indication. Le plus prescrit des AOD en France. Antidote disponible (andexanet alfa).',
    ...s(`**DCI :** Rivaroxaban\n**Noms commerciaux :** Xarelto®\n\n**Mécanisme d'action**\nInhibiteur direct, sélectif et réversible du facteur Xa libre et lié au caillot. Bloque la conversion de la prothrombine en thrombine. Absorption orale complète (biodisponibilité 80-100% avec repas pour doses élevées).\n\n**Indications principales**\n- Prévention AVC/embolie systémique dans la FA non valvulaire\n- Traitement et prévention secondaire TVP/EP\n- Prophylaxie MTEV post-chirurgie orthopédique majeure\n- Prévention des événements athérothrombotiques (à faible dose 2,5 mg x 2/j avec aspirine)\n\n**Posologie adulte**\n- FA : 20 mg/j avec repas du soir\n- TVP/EP aigu : 15 mg x 2/j 3 semaines, puis 20 mg/j\n- Prophylaxie orthopédique : 10 mg/j\n\n**Contre-indications**\n- DFG < 15 mL/min\n- Hémorragie active\n- Prothèse valvulaire mécanique\n\n**Effets indésirables**\n- Hémorragies (majorité des effets graves)\n- Élévation des transaminases (rare)\n- Pas de TIH\n\n**Antidote :** Andexanet alfa (Ondexxya®) — inhibiteur de facteur Xa\n\n**Surveillance infirmière**\n- Prendre avec repas aux doses 15 mg et 20 mg (absorption)\n- Surveiller signes hémorragiques\n- Contrôle rénal annuel\n- Pas d'adaptation de dose selon INR`, ['AOD', 'rivaroxaban', 'anti-Xa', 'FA', 'TVP', 'EP', 'andexanet alfa']) },

  { classIndex: 4, name: 'Apixaban (Eliquis®)', genericName: 'Apixaban', description: 'AOD inhibiteur direct du facteur Xa. 2 prises/j. Moins dépendant de la fonction rénale que les autres AOD. Profil hémorragique favorable.',
    ...s(`**DCI :** Apixaban\n**Noms commerciaux :** Eliquis®\n\n**Mécanisme d'action**\nInhibiteur oral direct et sélectif du facteur Xa. Biodisponibilité 50%. Élimination mixte : fécale 55% + rénale 27% → moins dépendant de la fonction rénale que le rivaroxaban ou le dabigatran.\n\n**Indications principales**\n- FA non valvulaire (prévention AVC)\n- TVP et EP (traitement et prévention secondaire)\n- Prophylaxie MTEV post-chirurgie orthopédique\n\n**Posologie adulte**\n- FA : 5 mg x 2/j (2,5 mg x 2/j si ≥ 2 critères : âge ≥ 80 ans, poids ≤ 60 kg, créatinine ≥ 133 μmol/L)\n- TVP/EP aigu : 10 mg x 2/j 7 jours, puis 5 mg x 2/j\n- Prophylaxie orthopédique : 2,5 mg x 2/j\n\n**Contre-indications**\n- DFG < 15 mL/min (précaution dès < 25 mL/min pour TVP/EP)\n- Hémorragie active, prothèse valvulaire mécanique\n\n**Effets indésirables**\n- Hémorragies\n- Anémie (hémorragies occultes)\n- Pas de TIH\n\n**Antidote :** Andexanet alfa (Ondexxya®)\n\n**Surveillance infirmière**\n- Prise avec ou sans repas (flexible)\n- Surveillance rénale moins critique mais annuelle\n- Éduquer sur les signes hémorragiques\n- 2 prises/j : risque d'oubli`, ['AOD', 'apixaban', 'anti-Xa', 'FA', 'TVP', 'moins rénal', 'andexanet alfa']) },

  { classIndex: 4, name: 'Fondaparinux (Arixtra®)', genericName: 'Fondaparinux sodique', description: 'Pentasaccharide de synthèse, inhibiteur sélectif du facteur Xa. Pas de risque de TIH. Injection SC 1 fois/j.',
    ...s(`**DCI :** Fondaparinux sodique\n**Noms commerciaux :** Arixtra®\n\n**Mécanisme d'action**\nPentasaccharide synthétique, analogue de la séquence pentasaccharidique de l'héparine qui se lie à l'antithrombine III. Inhibe sélectivement le facteur Xa. N'interagit pas avec les plaquettes → pas de risque de TIH (mécanisme de la TIH implique la thrombine et PF4).\n\n**Indications principales**\n- Prévention MTEV en chirurgie orthopédique et abdominale (indiqué quand HBPM contre-indiquée par risque TIH)\n- Traitement TVP et EP\n- SCA (NSTEMI, angor instable) sans angioplastie urgente\n\n**Posologie adulte**\n- Préventive : 2,5 mg SC x 1/j\n- Curative (TVP < 50 kg) : 5 mg SC x 1/j; (50-100 kg) : 7,5 mg; (> 100 kg) : 10 mg\n\n**Contre-indications**\n- DFG < 30 mL/min\n- Hémorragie active\n\n**Effets indésirables**\n- Hémorragies\n- Pas de TIH\n- Hématome au site d'injection\n\n**Surveillance infirmière**\n- Pas de surveillance plaquettaire systématique (pas de TIH)\n- Surveiller la fonction rénale (DFG)\n- Injection SC dans la paroi abdominale, alterner les sites\n- Pas d'antidote spécifique disponible`, ['fondaparinux', 'anti-Xa', 'anticoagulant', 'sans TIH', 'MTEV', 'SCA', 'pentasaccharide']) },

  { classIndex: 4, name: 'Nadroparine (Fraxiparine®)', genericName: 'Nadroparine calcique', description: 'HBPM à injection SC 1 à 2 fois/j selon indication. Préventive ou curative pour la MTEV. Disponible avec plusieurs concentrations.',
    ...s(`**DCI :** Nadroparine calcique\n**Noms commerciaux :** Fraxiparine®, Fraxodi® (1 prise/j)\n\n**Mécanisme d'action**\nHBPM : inhibition préférentielle du facteur Xa (anti-Xa) et moindre du facteur IIa. Même classe que l'énoxaparine, utilisation interchangeable dans certains protocoles (adaptation posologique nécessaire — pas d'équivalence mg/mg).\n\n**Indications principales**\n- Prévention MTEV en chirurgie et médecine\n- Traitement curatif TVP et EP\n- SCA (NSTEMI)\n- Prévention coagulation dans les circuits de dialyse\n\n**Posologie adulte**\n- Préventive : 2 850 UI anti-Xa SC x 1/j ou 38 UI/kg x 1/j (haut risque)\n- Curative : 85,5 UI/kg SC x 2/j ou 171 UI/kg x 1/j (Fraxodi®)\n\n**Contre-indications**\n- ATCD TIH\n- Hémorragie active\n- DFG < 30 mL/min (précaution)\n\n**Effets indésirables**\n- Hémorragies\n- TIH type II (rare)\n- Hématomes au site d'injection\n\n**Surveillance infirmière**\n- NFS-plaquettes J1, J5, J7, J10 (surveillance TIH)\n- Anti-Xa si nécessaire\n- Technique SC rigoureuse (abdomen, 90°, ne pas frotter)`, ['HBPM', 'nadroparine', 'Fraxiparine', 'anticoagulant', 'anti-Xa', 'MTEV', 'dialyse']) },

  { classIndex: 4, name: 'Acénocoumarol (Sintrom®)', genericName: 'Acénocoumarol', description: 'AVK à courte demi-vie (8-11h), permettant un équilibrage plus rapide mais une instabilité plus fréquente de l\'INR. Alternative à la warfarine.',
    ...s(`**DCI :** Acénocoumarol\n**Noms commerciaux :** Sintrom®, Minisintrom®\n\n**Mécanisme d'action**\nAVK (coumarine) de courte demi-vie (8-11 h, vs 36-42 h pour la warfarine). Même mécanisme : inhibition de la vitamine K époxyde réductase → blocage des facteurs II, VII, IX, X. Équilibre de l'INR plus rapide mais moins stable (nécessite contrôles plus fréquents).\n\n**Indications principales**\n- Mêmes que la warfarine : FA, prothèses valvulaires, TVP, EP\n- Préféré parfois pour son équilibrage plus rapide lors de la mise en route\n\n**Posologie adulte**\n- 1-8 mg/j selon INR cible, en 1 prise le soir\n- Contrôle INR J2-J3 après initiation\n\n**Contre-indications**\n- Hémorragie active\n- Grossesse\n- Même que tous les AVK\n\n**Effets indésirables**\n- Hémorragies (surdosage ou interactions médicamenteuses/alimentaires)\n- INR plus instable (demi-vie courte)\n\n**Antidote :** Vitamine K1, PFC, Octaplas®\n\n**Surveillance infirmière**\n- INR plus fréquents au début (demi-vie courte = instabilité plus fréquente)\n- Carnet de surveillance AVK\n- Mêmes précautions que pour la warfarine\n- Éduquer sur les aliments riches en vitamine K`, ['AVK', 'acénocoumarol', 'anticoagulant oral', 'INR', 'courte demi-vie', 'FA', 'prothèse valvulaire']) },

  { classIndex: 4, name: 'Tinzaparine (Innohep®)', genericName: 'Tinzaparine sodique', description: 'HBPM à 1 injection sous-cutanée par jour pour le traitement curatif. Profil de sécurité favorable en oncologie.',
    ...s(`**DCI :** Tinzaparine sodique\n**Noms commerciaux :** Innohep®\n\n**Mécanisme d'action**\nHBPM avec ratio anti-Xa/anti-IIa = 1,9:1. 1 injection SC par jour en curatif. Profil pharmacocinétique permettant un usage prolongé en cancérologie (thromboses associées aux cancers — préférence aux HBPM sur les AOD en oncologie).\n\n**Indications principales**\n- Traitement curatif de la TVP proximale et de l'EP\n- Prévention MTEV en chirurgie orthopédique\n- Thromboses associées aux cancers (traitement préférentiel 3-6 mois)\n\n**Posologie adulte**\n- Curative TVP/EP : 175 UI/kg SC x 1/j\n- Préventive : 3 500 UI SC x 1/j (risque modéré) ou 4 500 UI x 1/j (risque élevé)\n\n**Contre-indications**\n- ATCD TIH\n- Hémorragie active\n- DFG < 20 mL/min\n\n**Effets indésirables**\n- Hémorragies\n- TIH (rare)\n- Ostéoporose (usage prolongé)\n\n**Surveillance infirmière**\n- NFS-plaquettes (dépistage TIH)\n- Anti-Xa si nécessaire (oncologie, extrêmes de poids)\n- Avantage : 1 seule injection/j → meilleure observance à domicile\n- Technique SC : alternance des sites`, ['HBPM', 'tinzaparine', 'Innohep', 'anticoagulant', 'oncologie', 'TVP', '1 fois par jour']) },
];

/* ══════════════════════════════════════════════════════════════
   CLASSE 5 — Corticoïdes
══════════════════════════════════════════════════════════════ */

const corticoides = [

  { classIndex: 5, name: 'Prednisolone (Solupred®)', genericName: 'Prednisolone', description: 'Corticoïde forme active de la prednisone (métabolite actif). Ne nécessite pas de transformation hépatique. Préféré en cas d\'insuffisance hépatique.',
    ...s(`**DCI :** Prednisolone\n**Noms commerciaux :** Solupred® (comprimés orodispersibles), Prednisolone Mylan®\n\n**Mécanisme d'action**\nGlucocorticoïde de synthèse, forme active (ne nécessite pas de transformation hépatique contrairement à la prednisone). Même puissance anti-inflammatoire et immunosuppressive. Avantage en cas d'insuffisance hépatique.\n\n**Indications principales**\n- Mêmes que la prednisone\n- Préféré en cas d'insuffisance hépatocellulaire sévère\n- Maladies inflammatoires, auto-immunes, allergiques sévères\n- Transplantation\n\n**Posologie adulte**\n- 0,5-1 mg/kg/j le matin (rythme circadien)\n- Forme orodispersible : facilite l'administration chez les patients ayant du mal à avaler\n\n**Contre-indications**\n- (Relatives) : infections non contrôlées, ulcère actif\n\n**Effets indésirables**\n- Identiques à la prednisone : diabète cortisonique, ostéoporose, HTA, Cushing\n\n**Surveillance infirmière**\n- Ne jamais arrêter brutalement\n- Glycémie, PA, poids régulièrement\n- Calcium + vitamine D + biphosphonate si traitement prolongé`, ['corticoïde', 'prednisolone', 'Solupred', 'forme active', 'anti-inflammatoire', 'immunosuppresseur']) },

  { classIndex: 5, name: 'Méthylprednisolone (Médrol®)', genericName: 'Méthylprednisolone', description: 'Corticoïde de synthèse disponible en formes orales et injectable (Solu-Médrol®). Utilisé pour les bolus de corticothérapie IV dans les maladies inflammatoires aiguës.',
    ...s(`**DCI :** Méthylprednisolone (acétate ou succinate sodique)\n**Noms commerciaux :** Médrol® (oral), Solu-Médrol® (IV), Depo-Médrol® (IA)\n\n**Mécanisme d'action**\nGlucocorticoïde 4-5 fois plus puissant que la prednisone. Minime effet minéralocorticoïde. Forme succinate sodique (Solu-Médrol®) hydrosoluble → utilisation IV possible en bolus (« pulse » de corticothérapie).\n\n**Indications principales**\n- Bolus IV : poussées sévères de maladies auto-immunes (lupus, vascularites, SEP), rejet de greffe aigu\n- Oral (Médrol®) : maladies inflammatoires chroniques\n- Intra-articulaire (Depo-Médrol®) : arthrites inflammatoires localisées\n\n**Posologie adulte**\n- Bolus IV : 500 mg à 1 g/j x 3 jours (sous surveillance hospitalière)\n- Oral : 4-48 mg/j en fonction de l'indication\n- IA : 20-40 mg selon l'articulation\n\n**Contre-indications**\n- Infections virales systémiques, infections fungiques non traitées\n- Vaccination par vaccin vivant\n\n**Effets indésirables**\n- Bolus IV : arythmies cardiaques possibles (surveillance monitoring)\n- Mêmes effets systémiques que les autres corticoïdes\n\n**Surveillance infirmière**\n- Bolus IV : monitoring cardiaque (ECG), surveillance PA et glycémie\n- Injection IV lente (30-60 min minimum)\n- Surveillance des infections opportunistes après bolus`, ['corticoïde', 'méthylprednisolone', 'Solu-Médrol', 'bolus', 'IV', 'auto-immune', 'rejet de greffe']) },

  { classIndex: 5, name: 'Dexaméthasone (Dectancyl®)', genericName: 'Dexaméthasone', description: 'Corticoïde fluoré très puissant (7x prednisone). Sans effet minéralocorticoïde. Utilisé dans l\'œdème cérébral, les nausées chimio, l\'ARDS et le COVID-19 sévère.',
    ...s(`**DCI :** Dexaméthasone (base ou phosphate sodique)\n**Noms commerciaux :** Dectancyl®, Dexaméthasone Mylan®, Neomycin-Dexaméthasone® (ophtalmique)\n\n**Mécanisme d'action**\nGlucocorticoïde fluoré, 7 fois plus puissant que la prednisone. AUCUN effet minéralocorticoïde → pas de rétention hydrosodée. Demi-vie longue (36-54 h). Passe la barrière hémato-encéphalique.\n\n**Indications principales**\n- Œdème péri-tumoral cérébral (10 mg IV puis 4 mg x 4/j)\n- Méningites bactériennes (réduction séquelles neurologiques)\n- Nausées/vomissements chimio-induits (anti-émétique adjuvant)\n- ARDS modéré/sévère (≥ 4 mg/j, étude DEXA-ARDS)\n- COVID-19 sévère sous O2 ou ventilation (RECOVERY trial)\n- Test de freinage (diagnostic syndrome de Cushing)\n\n**Posologie adulte**\n- Œdème cérébral : 10 mg IV puis 4 mg x 4/j\n- Anti-émétique chimio : 8-12 mg IV avant la chimio\n- ARDS/COVID : 6-8 mg/j IV ou PO\n\n**Contre-indications**\n- (Relatives) : infections actives non contrôlées\n\n**Effets indésirables**\n- Diabète cortisonique (fréquent, potentiel élevé glucocorticoïde)\n- Immunodépression\n- Pas de rétention hydrosodée (avantage vs autres corticoïdes)\n\n**Surveillance infirmière**\n- Glycémie capillaire pluri-quotidienne\n- Surveiller infections opportunistes\n- Administration IV lente`, ['corticoïde', 'dexaméthasone', 'fluoré', 'puissant', 'œdème cérébral', 'COVID-19', 'anti-émétique']) },

  { classIndex: 5, name: 'Bétaméthasone (Célestène®)', genericName: 'Bétaméthasone', description: 'Corticoïde fluoré, isomère de la dexaméthasone. Utilisé pour la maturation pulmonaire fœtale (prématurité) et les maladies inflammatoires.',
    ...s(`**DCI :** Bétaméthasone (valerate, dipropionate, phosphate disodique)\n**Noms commerciaux :** Célestène® (IV/IM), Betesil® (cutané), Diprosone® (cutané)\n\n**Mécanisme d'action**\nGlucocorticoïde fluoré, puissance équivalente à la dexaméthasone (7x prednisone). Isomère de configuration. Pas d'effet minéralocorticoïde. Excellente pénétration cutanée (formes topiques).\n\n**Indications principales**\n- Maturation pulmonaire fœtale en cas de prématurité menaçante (2 injections IM à 24h d'intervalle → injection la plus importante en obstétrique)\n- Maladies inflammatoires systémiques (voie IV/IM)\n- Dermatoses inflammatoires (formes cutanées topiques)\n- Péri-articulaire, intra-articulaire, péri-nerveux\n\n**Posologie adulte**\n- Maturation fœtale : 12 mg IM J1 et J2 (avant 34 SA)\n- Anti-inflammatoire : 0,5-9 mg/j IV ou IM\n\n**Contre-indications**\n- (Relatives) : infections actives\n- Formes cutanées : éviter visage, plis, longues durées\n\n**Effets indésirables**\n- Effets systémiques si usage prolongé ou topique étendu\n- Hyperglycémie transitoire chez la mère (surveillance)\n\n**Surveillance infirmière**\n- Maturation fœtale : surveiller la glycémie maternelle (surtout diabétiques)\n- Monitorage fœtal après injection (tachycardie fœtale possible)\n- Formes topiques : ne pas appliquer en occlusion sur de grandes surfaces`, ['corticoïde', 'bétaméthasone', 'fluoré', 'maturation pulmonaire', 'prématurité', 'obstétrique', 'Célestène']) },

  { classIndex: 5, name: 'Hydrocortisone (Hydrocortisone Roussel®)', genericName: 'Hydrocortisone (cortisol)', description: 'Corticoïde identique au cortisol naturel. Utilisé dans l\'insuffisance surrénalienne aiguë (traitement de substitution) et dans le choc septique réfractaire.',
    ...s(`**DCI :** Hydrocortisone (acétate ou succinate sodique)\n**Noms commerciaux :** Hydrocortisone Roussel® (IV), Cortef® (oral), Hydrocortisone Pierre Fabre® (topique)\n\n**Mécanisme d'action**\nCortisol synthétique identique au cortisol endogène. Effets glucocorticoïdes ET minéralocorticoïdes (rétention sodée). Faible puissance glucocorticoïde (1x, référence). Remplace le cortisol déficient dans l'insuffisance surrénalienne.\n\n**Indications principales**\n- Insuffisance surrénalienne aiguë (crise addisonienne) — URGENCE\n- Substitution dans l'insuffisance surrénalienne chronique primaire (maladie d'Addison)\n- Hyperplasie congénitale des surrénales\n- Choc septique réfractaire (200 mg/j en IVSE)\n- Maladies allergiques sévères aiguës (IV : urticaire géante, choc anaphylactique en complément de l'adrénaline)\n\n**Posologie adulte**\n- Crise addisonienne : 100 mg IV bolus, puis 200 mg/24h IVSE\n- Substitution chronique : 15-25 mg/j PO en 2-3 prises (matin +++)\n- Choc septique : 200 mg/24h IVSE x 7 j si choc réfractaire aux vasopresseurs\n\n**Contre-indications**\n- Aucune absolue en urgence vitale\n- Infections non contrôlées (en dehors de l'urgence)\n\n**Effets indésirables**\n- Rétention hydrosodée (effet minéralocorticoïde) : surveiller PA, poids, œdèmes\n- Hypokaliémie\n\n**Surveillance infirmière**\n- Crise addisonienne : URGENCE — remplissage vasculaire + hydrocortisone IV simultanément\n- Natrémie, kaliémie, glycémie en urgence\n- Substitution chronique : éduquer à tripler la dose lors de stress (fièvre, chirurgie, traumatisme)`, ['corticoïde', 'hydrocortisone', 'cortisol', 'insuffisance surrénalienne', 'Addison', 'choc septique', 'substitution']) },

  { classIndex: 5, name: 'Triamcinolone (Kénacort®)', genericName: 'Triamcinolone acétonide', description: 'Corticoïde fluoré à dépôt, pour infiltrations intra-articulaires et péri-articulaires. Durée d\'action prolongée (3-4 semaines). Pas de forme systémique orale.',
    ...s(`**DCI :** Triamcinolone acétonide\n**Noms commerciaux :** Kénacort Retard® (IA), Tricone® (IA), Nasacort® (nasal)\n\n**Mécanisme d'action**\nCorticoïde fluoré de dépôt (formulation microcristalline à libération prolongée). Après injection locale, libération lente sur 3-4 semaines → effet anti-inflammatoire local durable. Absorption systémique minime mais réelle (surveillance glycémique).\n\n**Indications principales**\n- Infiltrations intra-articulaires : poussées d'arthrose du genou, hanche, épaule\n- Infiltrations péri-articulaires : tendinites (épicondylite, coiffe des rotateurs), capsulite\n- Infiltrations épidurales (douleurs radiculaires)\n- Localement : dermatoses kéloïdes, lichen plan\n\n**Posologie adulte**\n- IA genou : 40 mg (1 ampoule de 1 mL)\n- IA petites articulations : 10 mg\n- Maximum 3-4 infiltrations par an par articulation\n\n**Contre-indications**\n- Infection locale ou générale active (absolue pour IA)\n- Hémarthrose (si coagulation perturbée)\n- Allergie au produit\n\n**Effets indésirables**\n- Flush (bouffée vasomotrice dans les 24h post-infiltration)\n- Hyperglycémie transitoire (diabétiques ++)\n- Atrophie cutanée et sous-cutanée si injection superficielle\n- Arthropathie cortisonique (si trop fréquentes)\n\n**Surveillance infirmière**\n- Contrôle glycémie chez le diabétique dans les 48h\n- Zone stérile : préparation avec asepsie chirurgicale\n- Informer sur le flush (normal, transitoire)\n- Repos relatif 24-48h après infiltration articulaire`, ['corticoïde', 'triamcinolone', 'infiltration', 'intra-articulaire', 'arthrose', 'tendinite', 'dépôt']) },

  { classIndex: 5, name: 'Budésonide (Entocort®)', genericName: 'Budésonide', description: 'Corticoïde à action locale intestinale, avec forte métabolisation hépatique du premier passage limitant les effets systémiques. Utilisé dans la maladie de Crohn iléo-cæcale.',
    ...s(`**DCI :** Budésonide\n**Noms commerciaux :** Entocort® (oral LP), Jorveza® (comprimés gastrorésistants), Pulmicort® (inhalé), Rhinocort® (nasal)\n\n**Mécanisme d'action**\nGlucocorticoïde à haute potence locale mais forte extraction hépatique de premier passage (~90%) → effets systémiques très réduits comparés aux corticoïdes classiques. Formulation LP ciblant l'iléon terminal et le côlon ascendant (Entocort®).\n\n**Indications principales**\n- Maladie de Crohn iléo-cæcale légère à modérée (Entocort® — alternative aux corticoïdes systémiques)\n- Colite microscopique (Jorveza®)\n- Asthme (forme inhalée Pulmicort®)\n- Rhinite allergique (Rhinocort®)\n\n**Posologie adulte**\n- Maladie de Crohn : 9 mg/j en 1 prise le matin pendant 8 semaines, puis décroissance\n- Colite microscopique : 9 mg/j\n\n**Contre-indications**\n- Infections intestinales actives\n- Cirrhose (réduction du premier passage hépatique → effets systémiques accrus)\n\n**Effets indésirables**\n- Moins d'effets systémiques que la prednisone\n- Acné, érythème facial léger (corticothérapie locale)\n- Légère suppression surrénalienne à long terme\n\n**Surveillance infirmière**\n- Ne pas écraser les gélules (libération prolongée ciblée)\n- Expliquer que le bénéfice est local (moins de prise de poids, moins de Cushing)\n- Surveillance quand même de la glycémie et de la PA (effets systémiques partiels)`, ['corticoïde', 'budésonide', 'Entocort', 'Crohn', 'MICI', 'local', 'faible effet systémique']) },

  { classIndex: 5, name: 'Fludrocortisone (Florinef®)', genericName: 'Fludrocortisone acétate', description: 'Seul minéralocorticoïde de synthèse disponible. Traitement de substitution de l\'insuffisance surrénalienne primaire (Addison). Puissant effet rétenteur de sel.',
    ...s(`**DCI :** Fludrocortisone acétate\n**Noms commerciaux :** Florinef®\n\n**Mécanisme d'action**\nCorticoïde fluoré à prédominance minéralocorticoïde (puissance aldostérone = 125x). Faible activité glucocorticoïde. Se lie aux récepteurs minéralocorticoïdes du tube contourné distal du rein → rétention sodée et excrétion potassique. Seul minéralocorticoïde oral disponible.\n\n**Indications principales**\n- Insuffisance surrénalienne primaire (maladie d'Addison) en complément de l'hydrocortisone\n- Hyperplasie congénitale des surrénales avec perte de sel\n- Hypotension orthostatique sévère idiopathique (hors AMM)\n\n**Posologie adulte**\n- Insuffisance surrénalienne : 0,05 à 0,2 mg/j per os en 1 prise\n- Titration selon la PA, la natrémie, la kaliémie et la rénine plasmatique\n\n**Contre-indications**\n- Insuffisance cardiaque\n- HTA sévère\n- Hypokaliémie préexistante\n\n**Effets indésirables**\n- Rétention hydrosodée, œdèmes\n- HTA (surdosage)\n- Hypokaliémie\n- Prise de poids\n\n**Surveillance infirmière**\n- Pesée quotidienne (rétention sodée)\n- PA et bilan ionique réguliers\n- Éduquer le patient à augmenter les apports sodés lors de chaleur, effort intense, diarrhées\n- Associé à l'hydrocortisone dans la maladie d'Addison — les deux sont indispensables`, ['corticoïde', 'fludrocortisone', 'minéralocorticoïde', 'Addison', 'substitution', 'rétention sodée', 'Florinef']) },

  { classIndex: 5, name: 'Déflazacort (Calcort®)', genericName: 'Déflazacort', description: 'Glucocorticoïde oxazoline dérivé de la prednisolone. Moins d\'effets métaboliques (moins diabétogène, moins de prise de poids) à équipotence anti-inflammatoire.',
    ...s(`**DCI :** Déflazacort\n**Noms commerciaux :** Calcort®\n\n**Mécanisme d'action**\nGlucocorticoïde oxazoline, prodrogue métabolisée en 21-désacétyl-déflazacort (actif). Équipotence anti-inflammatoire avec la prednisone (1,5 mg déflazacort = 1 mg prednisone). Moins de rétention hydrosodée, moins d'effet diabétogène, moins d'ostéoporose selon certaines études.\n\n**Indications principales**\n- Maladies inflammatoires et auto-immunes nécessitant une corticothérapie prolongée chez des patients particulièrement à risque de complications métaboliques\n- Dystrophie musculaire de Duchenne (traitement approuvé en pédiatrie)\n- Polyarthrite rhumatoïde, maladies de système\n\n**Posologie adulte**\n- Équivalence : 1 mg prednisone = 1,3 mg déflazacort\n- 6-90 mg/j selon l'indication\n\n**Contre-indications**\n- (Relatives) : infections actives, ulcère gastroduodénal\n\n**Effets indésirables**\n- Mêmes que les autres corticoïdes mais potentiellement moins prononcés (métabolisme glucidique, lipidique)\n- Cataracte (à long terme)\n\n**Surveillance infirmière**\n- Glycémie, PA, poids (mêmes surveillances que les autres corticoïdes mais potentiellement avec moins d'anomalies)\n- Acuité visuelle (cataracte)\n- Supplémentation calcium + vitamine D`, ['corticoïde', 'déflazacort', 'moins diabétogène', 'Duchenne', 'maladies auto-immunes', 'métabolique']) },
];

module.exports = { iec, anticoagulants, corticoides };
